### ISSUE TITLE
Add GCE VM information as a label to the traces

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#100]
For people running on Compute Engine, it would be useful to be able to do filtering of the traces by VM. Right now the trace backend has no knowledge of which VM a particular trace was captured on. We should add this as a label on the traces. Once that is available, the UI can offer a way to filter by it. This issue only tracks the former.

**Comment by matthewloring** [comment]
@erikmcc Would it be possible to incorporate this into the API in some way or is the best approach to pass this information as a label on every reported trace.

**Comment by erikmcc** [comment]
A label is best.

**Comment by matthewloring** [comment]
@ofrobots Does the environment variable GAE_MINOR_VERSION used [here](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/lib/uid.js#L30) hold the information you want attached?

**Comment by ofrobots** [comment]
@matthewloring I don't think so. I think `GAE_MINOR_VERSION` is only available on AppEngine.

**Comment by matthewloring** [comment]
@ofrobots I'll use the hostname and id fields of the default metadata (https://cloud.google.com/compute/docs/metadata?hl=en#default).

**Comment by ofrobots** [comment]
SGTM.
