### ISSUE TITLE
Test trace-agent with the tutorial GCE workflow

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#101]
Here are the tutorial instructions on deploying to GCE: https://cloud.google.com/nodejs/getting-started/run-on-compute-engine
1. Make sure everything works for trace (e.g. the right scopes are added when the VM is created)
2. Update the tutorial above to include instructions on how to enable trace.

**Comment by matthewloring** [comment]
Clarification: linked instructions should work with trace.

**Comment by matthewloring** [comment]
@ofrobots The linked tutorial doesn't work for me without including any additional code for trace. I'll open a bug against it.

**Comment by matthewloring** [comment]
This was an issue on my part setting up the required APIs properly. I'll give it another go.

**Comment by matthewloring** [comment]
I was able to get traces displaying for the above tutorial by adding the steps below before starting the section "Deploying a single instance":

1) add to top of app.js: require('@google/cloud-trace').start();
2) npm install --save @google/cloud-trace
3) enable trace api in developer console

I didn't need to use a service account or custom credential. I can work to update the tutorial with these steps once we have a unified story for setting up cloud trace across GAE, GCE, and kubernetes. For now, we have confirmation that the flow works on GCE.

@ofrobots How does that sound?

**Comment by ofrobots** [comment]
SGTM.

**Comment by matthewloring** [comment]
Marking this closed then. We can open up an independent bug once we're ready to start integrating into official cloud documentation.
