### ISSUE TITLE
MVM: Add module labels to the captured traces

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#169]
From an email bug report:
> [...] individual traces are not correctly associated with their module, ie. default, worker, etc. They only appear in Pantheon if I select "All modules"

**Comment by jonparrott** [comment]
To add to this, should GCE VMs in general use their hostname as the module?

**Comment by ofrobots** [comment]
Client side fix landed, but there might be an issue on the service side. Re-opening until the service side issue is resolved.

**Comment by ofrobots** [comment]
Fixes landed in f1fa3819138e616f946476b7b362eebb020afa1d and 4471696cac16ad75ab5f896009699141908a9788. We'll try to get these into a release later in the week.

Also included is the change for GCE/GKE VMs to report their hostname as the module. Thanks for the suggestion!
