### ISSUE TITLE
Figure out how to add googlebot to do automatic CLA checks

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#18]

**Comment by matthewloring** [comment]
@ofrobots This should be all set up now. Do we need to wait for external contributors to see whether it's working correctly?

**Comment by ofrobots** [comment]
Even our own PRs should start getting checked by the bot. Let's close this when we've verified that it works.

**Comment by matthewloring** [comment]
Confirmed working, see https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/45
