### ISSUE TITLE
request is loaded by our dependencies before we can patch setImmediate

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-trace-nodejs#182]

**Comment by matthewloring** [comment]
We do not currently patch request. Isn't it the underlying http require done by request that is problematic?

**Comment by ofrobots** [comment]
Updated the title to make it more accurate. The problem is that we need to patch `setImmediate` (indirectly through CLS) before `request` is loaded. `request` caches the value of `setImmediate`.
