### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#221]
I want to try this with hapi 13 but it seems like the module has not been published in a while.
Is this for a reason and if so when can I expect a new release? I really want to try this.

Also what is the command to log debug info to console (like `DEBUG=cloud-trace node server`)?

**Comment by matthewloring** [comment]
You can get debug info by running `GCLOUD_TRACE_LOGLEVEL=4 node server.js`. We will be doing a release soon but you can try out hapi 13 functionality by installing from master: `npm install GoogleCloudPlatform/cloud-trace-nodejs`.

**Comment by AdriVanHoudt** [comment]
Cool thanks!

**Comment by AdriVanHoudt** [comment]
Ok did some testing on dev and looks nice!
Will enable on staging env for more testing.
Also Mysql did not seem to be logged due to no root. Logs:  `Untraced mysql query:` (I don't know what it means but just letting you know :P)
I am using https://www.npmjs.com/package/hapi-plugin-mysql for my sql connection, not sure if related.
Also I am using ioredis, is this package supported?

**Comment by matthewloring** [comment]
Thank you for the log information. #222 should get mysql reporting working with your plugin. We do not currently have plans to support ioredis but do have support for [node redis](https://www.npmjs.com/package/redis).

**Comment by AdriVanHoudt** [comment]
Very cool! Also awesome that you used a module I wrote to test :O 
Is there a reason you chose node_redis instead of ioredis? (they have plan to merge but no idea on the timeline on that)

**Comment by matthewloring** [comment]
We went with node_redis due to its popularity but we hope to increase the number of frameworks we can support over time.

**Comment by AdriVanHoudt** [comment]
Redis usage is not significant for atm so fine maybe I can do a shot at a PR after my vacation

**Comment by AdriVanHoudt** [comment]
Thanks for the help and the great work!

**Comment by matthewloring** [comment]
Thanks for trying it out. I'm glad the information is useful!
