### ISSUE TITLE
Mysql tracing in Async.parallel

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#223]
MySQL tracing in Async.parallel seems to show cumulative,
I checked a few traces and this happens in others as well so not just coincidence and there are that are not like that so in general it is definatly working 
![](http://puu.sh/nTf73/d72e110972.png)

**Comment by matthewloring** [comment]
When spans are displayed by the UI, spans with the same start time are ordered by end time leading to the monotonic pattern you're seeing. The spans are not cumulative, but many of them happen to start at the same time due to the use of Async.parallel. I believe what you're seeing here is correct.

**Comment by AdriVanHoudt** [comment]
Ah so they start at the same time and the longest is just sorted last?

**Comment by matthewloring** [comment]
Precisely, the UI has no other mechanism to know the true ordering of requests with the same start time.

**Comment by AdriVanHoudt** [comment]
Ah I see, thanks!
