### ISSUE TITLE
Local development: Trace error

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-trace-nodejs#257]
When developing locally, I get this error.

The error mentions project 32555940559 is. 
It is not the number of the one I am currently developing for. I have no idea what this error is about.

```
ERROR:@google/cloud-trace: TraceWriter: error:  403 { [Error: Stackdriver Trace API has not been used in project 32555940559 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudtrace/overview?project=32555940559 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.]
  code: 403,
  errors:
   [ { message: 'Stackdriver Trace API has not been used in project 32555940559 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudtrace/overview?project=32555940559 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
       domain: 'global',
       reason: 'forbidden' } ] }
```

**Comment by cheee** [comment]
This is because you used `gcloud auth login`. The project number:  32555940559 is gcloud project number. You should use: `gcloud beta auth application-default login`. Once you did that, the issue should go away.

**Comment by steren** [comment]
This is local development, I do not want to use Trace locally so I would prefer not have to do the auth step.

Also, the error message could be much better: How I am supposed to know that 32555940559 is gcloud project number?

**Comment by matthewloring** [comment]
If you would like to disable trace locally you can set the `GCLOUD_TRACE_DISABLE` environment variable. The error message is coming from the trace service and they already have a bug tracking the improvement of this message.

**Comment by matthewloring** [comment]
We now have documentation of the mechanisms for disabling the agent for local development (#259). I'll close this for now but please reopen if there are further improvements to be made.
