### ISSUE TITLE
Documentation not clear if I should use application default credentials on production

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-trace-nodejs#283]
The README says:

> if you are running your application on a machine where your are using the gcloud command line tools, and are logged using gcloud beta auth application-default login, you already have sufficient credentials, and a service account key is not required.

Does this mean that on a production GCE instance, it is OK to use application default credentials generated by gcloud? 
If not, I think we should change the doc to say to only use application default credentials on a local test environment.

**Comment by ofrobots** [comment]
I agree that while possible, application default creds shouldn't be recommended on GCE.
