### ISSUE TITLE
Update/release hapi support

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#291]
Currently all my tracing has stopped due to the `hapi v14 support` commit not being published yet. Now normally I would ask for a release but I believe hapi 15 will be release today or tomorrow so it might be interesting to wait. I took a quick look at the hapi hooks and I do not believe v15 will be a problem for this module.
Apart from that it might be interesting to release quicker since the last release was around 48 days ago 🙈

**Comment by matthewloring** [comment]
We are definitely overdue for a release. We will publish the v14 support now and can republish once v15 is out and we've verified it against the hooks.

**Comment by matthewloring** [comment]
Hapi v14 support is published. I'll keep an eye out for the v15 release!

**Comment by AdriVanHoudt** [comment]
Thanks a lot for the quick response! Want me to keep this issue open for v15?

**Comment by matthewloring** [comment]
Sounds good, 15 didn't require any logic changes so we just need to bump the supported versions. I have the PR open here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/293. Let's leave this issue open until that PR is landed and released.

**Comment by matthewloring** [comment]
All released! Thank you for opening this.

**Comment by AdriVanHoudt** [comment]
No problem! thanks for taking notice 🎉
