### ISSUE TITLE
Add support for cron jobs

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#299]
I know there is an issue about custom spans but I feel adding general support for cron jobs makes sense. These are most, if not all, of my background tasks and I think it is fairly easy to mock.
As a reference I am using https://github.com/ncb000gt/node-cron

Is this something that is possible at all?

**Comment by matthewloring** [comment]
We can definitely investigate patching node-cron but have a few other work items we need to get through first. We can leave this open to track a feature request for node-cron but hopefully the custom root span api from https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/289 will let you get the info you want from work done outside of a user request.

We are also happy to accept contributions for new module hooks, help with review, and run provided tests but cannot provide ongoing maintenance to support new versions.

**Comment by AdriVanHoudt** [comment]
Yeah I saw the custom root span issue but thought that cron jobs seemed a logical/easy thing to patch.

I will be at Node Interactive Amsterdam this week and I had some other oss planned, I'll see if I can squeeze in a PR, although this is something more low level then I am used to.

**Comment by matthewloring** [comment]
@AdriVanHoudt Have you gotten a chance to see whether the custom root span API is sufficient for your use case here?

**Comment by AdriVanHoudt** [comment]
I haven't gotten around to it sadly, Node Interactive was more busy than planned :P 
I would still very much like this feature and I would still like to try but sadly I don't have to much free coding time :/

**Comment by mattloring** [comment]
Tracing for node-cron sounds like a great opportunity to try out the [new plugin api](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md) to build your own plugin. If you do try out the plugin api, please let us know if you have any questions/feedback.

**Comment by AdriVanHoudt** [comment]
@matthewloring I was kind of waiting for the new api ;) when I have time I will definitely look into it!
