### ISSUE TITLE
Symlinked credentials are not supported

### ISSUE THREAD

**Issue by ggoodman** [GoogleCloudPlatform/cloud-trace-nodejs#303]
On Kubernetes, the recommended approach is to use a `Secret` object to provide the service account credentials for making trace requests. As of Kubernetes `1.3` volume-mounted secrets are implemented as symlinks and fail to be resolved by the depended-upon version of the auth library.

This means that logging on GKE via the recommended Kubernetes approach is broken.

The underlying issue has been fixed in google/google-auth-library-nodejs@785c514970a673e203795e18d77e5f273fd54f8d.

**Comment by matthewloring** [comment]
Thank you for alerting us. It appears the linked fix has not yet made it to a released version of `google-auth-library`. There are a few releases that will have to happen to pick this up: `google-auth-library` -> `@google/cloud-diagnostics-common` -> `@google/cloud-trace`. I'll update here as we get the releases rolled out.

**Comment by ggoodman** [comment]
Looking forward to this. I have a service deployed to production that is finding it inconvenient to stay alive and would love to have some better visibility into what's going on.

**Comment by matthewloring** [comment]
cc @tbetbetbe to get a release of the auth library including the above fix.

**Comment by matthewloring** [comment]
Today's release should include this fix. @ggoodman let me know whether things are working for you.

**Comment by matthewloring** [comment]
Closing this now that the fix is released. Feel free to reopen if you have any additional issues.
