### ISSUE TITLE
Add support for tracing swagger-tools

### ISSUE THREAD

**Issue by hach-que** [GoogleCloudPlatform/cloud-trace-nodejs#304]
This uses a very express-like framework for serving up APIs: https://github.com/apigee-127/swagger-tools

**Comment by matthewloring** [comment]
We can investigate patching swagger-tools officially but will have to assess the maintenance burden longer term. Our hooks rely on patching underneath the module interface and can be broken on minor version releases.

In the mean time, we are happy to accept community contributions for new module hooks, help with review, and run provided tests but may not provide ongoing maintenance to support new versions.

**Comment by matthewloring** [comment]
Does #305 fix this issue for you?

**Comment by hach-que** [comment]
I'll have a chance sometime later this week to switch back to cloud-trace-nodejs (currently using my forked GitHub repository so I can have this functionality in production).

**Comment by matthewloring** [comment]
@hach-que Any update on whether #305 fixes this?

**Comment by hach-que** [comment]
Yeah that branch comes straight from my fork which I was and still am using (haven't had a chance to switch back yet).

**Comment by matthewloring** [comment]
Ok, I'm going to close this for now. If there are any issues when you switch back please let us know.
