### ISSUE TITLE
Allow "Service Name" and "Service Version" to be set

### ISSUE THREAD

**Issue by hach-que** [GoogleCloudPlatform/cloud-trace-nodejs#306]
I'd like to be able to populate these fields in the Google Cloud Trace UI, so that I can do meaningful comparisons between versions of software deployed on Container Engine:

![image](https://cloud.githubusercontent.com/assets/504826/18865717/0873614e-84e0-11e6-881e-c2b71f45cdc5.png)

I tried to set the module name and version like this:

```
process.env.GAE_MODULE_NAME = '...';
try {
  process.env.GAE_MODULE_VERSION = require('./package.json').version;
} catch (ex) {
  console.error('Unable to obtain service version during early startup, this may prevent traces from working correctly:')
  console.error(ex);
}
var traceAgent = require('....'); // a version of cloud-trace-nodejs at the latest version with the connect PR merged in
traceAgent.start();
```

but it doesn't seem to populate (at least not while it's getting the initial trace sets).

**Comment by kjin** [comment]
The Cloud UI currently requires an existing App Engine instance with a given service/version pair in order for traces to show up under those fields. You would need a (dummy) App Engine instance for the Cloud UI to provide an entry in its drop-down menu.

You also need to provide `process.env.GAE_MINOR_VERSION`. You can set this to any value.

These fields are all intended to be set by GAE itself, so unfortunately if you are running on Container Engine (or anywhere other than GAE, for that matter) this workaround is the extent of what you can currently do. I do understand though that it would be more convenient for the UI to have the ability to filter traces from different version of an app outside of GAE, and I'm contacting the team that covers the Trace UI about what we can do about expanding the filtering options.

**Comment by kjin** [comment]
We've been told that you actually can filter by arbitrary label, through the 'request URI' bar (despite its naming). It's more verbose than using the drop-down menus, but it allows you to filter traces by services (modules) that aren't App Engine instances. For example, if you set module name and version like this:

```javascript
process.env.GAE_MODULE_NAME = 'dev';
process.env.GAE_MODULE_VERSION = 'v2';
process.env.GAE_MINOR_VERSION = '0';
var traceAgent = require('....');
traceAgent.start();
```

You can use the following query to filter those traces:

`trace.cloud.google.com/gae/app/module:dev trace.cloud.google.com/gae/app/module_version:v2`

**Comment by matthewloring** [comment]
@hach-que Does this query mechanism work for you?

**Comment by hach-que** [comment]
Yeah that seems to work for me.
