### ISSUE TITLE
cloud-trace 429 status code errors and rateLimitExceeded

### ISSUE THREAD

**Issue by Splaktar** [GoogleCloudPlatform/cloud-trace-nodejs#314]
Question about cloud-trace 429 errors that I started seeing this morning. 

My logs show a total of 59 requests in the last 24 hours with 5 of these errors and a 100k quota w/ 1k requests per 100s. So it seems clearly far under any of the quota limits.

But the errors are telling me that my quota is a problem. Is it possible that the service just had an interruption or other failure temporarily? or is this a bug in cloud-trace-nodejs?

``` 09:46:45.000
ERROR:@google/cloud-trace: TraceWriter: error: 429 { [Error: Resource has been exhausted (e.g. check quota).]
09:46:45.000
code: 429,
09:46:45.000
errors:
09:46:45.000
[ { message: 'Resource has been exhausted (e.g. check quota).',
09:46:45.000
domain: 'global',
09:46:45.000
reason: 'rateLimitExceeded' } ] }
```

I was also seeing a number of these during that time:

```
09:41:33.000
ERROR:@google/cloud-debug: Failed to re-register debuggee myprojectname: Error: socket hang up
```

**Comment by AdriVanHoudt** [comment]
I have also had this problem. 2 things.

Why is this error not being logged to stderr?
And can this be because of the GA of stackdriver?

**Comment by ofrobots** [comment]
Thanks for reporting the issue. We're investigating.

**Comment by ofrobots** [comment]
The Trace API team is investigating a potential disconnect between the actual and enforced quota limits.

**Comment by matthewloring** [comment]
@Splaktar @AdriVanHoudt The Trace API team has pushed a potential fix for this. Are you still observing the errors?

**Comment by AdriVanHoudt** [comment]
Haven't seen them but they are not being logged to my usual error logger so not sure :/

**Comment by matthewloring** [comment]
Closing this for now. Feel free to reopen if you have additional issues with the trace quota.
