### ISSUE TITLE
Preserve context across knex (generic-pool)

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#327]
Originally opened through: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/326.

It seems that [knex](https://www.npmjs.com/package/knex) is causing context loss, probably due to its use of [generic-pool](https://www.npmjs.com/package/generic-pool).

**Comment by matthewloring** [comment]
Fixed in: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/468
