### ISSUE TITLE
runInRootSpan always creates a context

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#330]
`runInRootSpan` always creates a trace context. This means that incoming trace context cannot be propagated by users of the custom tracing api.

One way to fix this would be to accept optional arguments in `runInRootSpan` with the optional context if the caller has one already.

/cc @evanlucas.

**Comment by evanlucas** [comment]
@ofrobots anything I can do to help on this?

**Comment by ofrobots** [comment]
@evanlucas we are presently hashing out the details of a new public plug-in API at the moment – once that is a bit more clear, we are going to decide on how to deal with the existing APIs. Stay tuned!

**Comment by ofrobots** [comment]
@evanlucas We have a Plugin API taking shape here which should solve the underlying issue here. Can you take a look at the API here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/356/files#diff-ddc56f43fbfec8cecb2a2860232c31f5 to see if it will address your use-case properly. Any other feedback would be greatly appreciated too.

We are hoping to land this as an experimental API soon.

**Comment by matthewloring** [comment]
The new api for creating context aware root spans is available in the 1.0.0 release of `@google-cloud/trace-agent`. @evanlucas Please let us know once you get a chance to try it out.

**Comment by evanlucas** [comment]
Yes, I had to chance to experiment with it and the problem appears to have been solved. Thanks a bunch!!

**Comment by matthewloring** [comment]
Awesome! Closing this for now. Feel free to reopen if you have any follow-on issues or questions!
