### ISSUE TITLE
Add more information the captured traces

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-trace-nodejs#34]
- [x] [MongoDB](#97)
- [x] MySQL
- [x] Redis
- [x] Restify
- [x] Hapi
- [x] Express (deferred render spans)
- [x] Http

**Comment by matthewloring** [comment]
@ofrobots Please verify information present on Hapi and Restify

**Comment by matthewloring** [comment]
Mongo #107 
Redis #144

**Comment by matthewloring** [comment]
MySQL #145

**Comment by ofrobots** [comment]
I think we can close this one now.

**Comment by matthewloring** [comment]
Yay!
