### ISSUE TITLE
express 3.1.0 not supported

### ISSUE THREAD

**Issue by rajeshpanwar** [GoogleCloudPlatform/cloud-trace-nodejs#340]
Hi Sir,

I have followed all installation steps, but not getting api trace.

How can i figure out what is going wrong ?

**Comment by matthewloring** [comment]
Our support for express starts at version 4 (https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#what-gets-traced). We do not currently have plans to extend support back to version 3 but we are happy to accept pull requests adding support to our agent for new module versions. We are also working on an API that would allow other modules to provide tracing support for modules/versions that our trace agent does not instrument.

**Comment by mattloring** [comment]
We do not currently intend to extend support for our trace instrumentation back to version 3.x. You are welcome to try out the [new plugin api](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md) to build your own plugin. If you do try out the plugin api, please let us know if you have any questions/feedback.
