### ISSUE TITLE
Add support for Postgres

### ISSUE THREAD

**Issue by melalj** [GoogleCloudPlatform/cloud-trace-nodejs#341]
That would be great to have an integration of trace with [pg](https://github.com/brianc/node-postgres) (like the one that is already possible with MySQL).

**Comment by ofrobots** [comment]
Thanks for opening the issue. I've tagged this as an enhancement request.

**Comment by ofrobots** [comment]
WIP PR here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/402

**Comment by matthewloring** [comment]
#402 has landed. Closing this for now but feel free to open new issues if you have any questions once you get a chance to try out the postgres plugin.
