### ISSUE TITLE
Request contains an invalid argument

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#342]
I am seeing this passing by but not logged to stderr so our error logging does not catch it.
* I suggest logging to stderr
* Can I debug this?

```js
 ERROR:@google/cloud-trace: TraceWriter: error:  400 { [Error: Request contains an invalid argument.]
   code: 400,
  errors:
    [ { message: 'Request contains an invalid argument.',
        domain: 'global',
       reason: 'badRequest' } ] }
```

**Comment by matthewloring** [comment]
Logging our error messages to stderr sounds like a good idea. We are currently in the process of moving to a new logger and can look into adding this behavior.

Do you see this error message regularly in your logs or was there only a single appearance? I would suggest setting `logLevel` to 4 in the config or setting the env variable `GCLOUD_LOG_LEVEL` to 4. This should cause the full buffer of traces to be printed before publishing. If you're able to share the trace buffer  that is being published when you see this message I can try to reproduce it on my machine.

**Comment by AdriVanHoudt** [comment]
I have the debug data but it is quite a lot and a bunch of personal/confidential information, is there way to share this privately?

**Comment by matthewloring** [comment]
You're welcome to create a private github gist or drive document and share it with me (mattloring@google.com) or use any other private sharing method you like. You can also scrub it if there are things you are not comfortable sharing but that may not be feasible given the size.

**Comment by matthewloring** [comment]
Alternatively, you could build the request that the agent is making manually using this information and narrow down the test case yourself but this will likely be time consuming.

Also, my above comment had a typo. The environment variable should be `GCLOUD_TRACE_LOGLEVEL` but it looks like you have things working.

**Comment by AdriVanHoudt** [comment]
I shared a google drive txt with you, be ware it is quite the data.
And yeah narrowing it down would be kind of time consuming :D 
And I saw haha I used the config option instead :P

**Comment by matthewloring** [comment]
It looks like the publish was almost a megabyte in size. I will investigate things locally but could you try specifying `bufferSize: 5` in your configuration? I suspect this request is just too large for the trace service.

**Comment by matthewloring** [comment]
It appears that one of the labels on a span is too large for the service and is being rejected. Once I determine the max label size we can make sure the agent doesn't try to publish labels that are too large. In the meantime, turning off `enhancedDatabaseReporting` should let all traces be published.

**Comment by AdriVanHoudt** [comment]
I don't want to turn of enhancedDatabaseReporting since I will not mysql tracing then, which is super handy for debugging.
I told you it wa quite the data ;) setting buffersize to 5 does what exactly?
I also see a lot of `object object` in the trace, I always thought this was an issue with the console (and reported it there a while ago) but it seems the agent is sending that. Is that by design?

**Comment by matthewloring** [comment]
When you first shared the data, I suspected that the set of traces were too large. Setting the buffer size to 5 would reduce the number of spans buffered before publishing which should reduce the size of the request made to the service. After digging into the data you were sending, I found that the service rejects labels attached to spans that are more than 16k in size. Some of the labels on the mysql spans were over this size limit. We will have to summarize database queries/results that get too large.

The `object object`s you see in traces were not intentional on our end. We will look into that as a separate bug.

**Comment by matthewloring** [comment]
A fix for the large labels is put together here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/345.

A proposed fix for the `object object` problem is in the works here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/346 but may take some more iteration. We'll be getting a release out with the label fix soon.

**Comment by AdriVanHoudt** [comment]
Thanks for all the fixes 🙏 
I think only the `log to stderr` thingy is left

**Comment by matthewloring** [comment]
The above fixes have been released with v0.6.0. We will soon be moving to a new logger so I'm going to put the logging to stderr item in the backlog once we have the new logger. Just to have some more information, what tools are you using to track stderr v stdout?

**Comment by AdriVanHoudt** [comment]
We track errors through either random throws, or via hapi logging and then log to opbeat. I saw this log passing by when monitoring the output of good-console (hapi logging to console) through pm2. When you log an actual error it shows up in the error stream of pm2 while this is error was not.

**Comment by matthewloring** [comment]
OK, it looks like the primary issue on this bug (failed publishes) has been addressed. @AdriVanHoudt would you be OK with closing this issue if things are working again and opening a separate issue to discuss how the trace agent should log operational errors?

It sounds like maybe the actual logging problem here is that we do not log a stack trace making it seem to pm2 like it is not an error?

**Comment by AdriVanHoudt** [comment]
@matthewloring yeah the main thing is fixed

I think the issue is that you are logging a custom thing and not a real error (wild guess) and not having a stacktrace does not help ^^ (fine to open new issue btw)
