### ISSUE TITLE
Add stack traces to logged errors

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-trace-nodejs#349]
Errors logged by the agent coming from the trace service do not include the actual error object. This prevents them from being detected by tools that scan stdout/stderr such as `pm2`. We should include the full error object if it is available.

Original discussion here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/342.

/cc @AdriVanHoudt

**Comment by AdriVanHoudt** [comment]
This ties in with work on a new logger although I could not quickly find it to link it

**Comment by matthewloring** [comment]
Stack traces should now be printed for these network errors after #394.
