### ISSUE TITLE
e2e test running on google cloud platform

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-trace-nodejs#35]
Test for span quality and memory leaks

**Comment by matthewloring** [comment]
@ofrobots I have [this](https://github.com/matthewloring/cloud-trace-performance) performance test running daily on a cron job with the bookshelf app deployed to a GAE instance and the load being driving by a GCE instance. I haven't seen any issues with flaky performance results yet but we should look through it to make sure we're satisfied with the integrity of the numbers I'm getting.

**Comment by ofrobots** [comment]
Is the load driven from the same instance, or are there two instances involved?

**Comment by matthewloring** [comment]
There are two instances, an app engine deployment and an independent CGE load driver.

**Comment by ofrobots** [comment]
I think what remains to be done for this is:
1. Make sure we are satisfied with the integrity of the performance numbers we are getting.
2. Store the performance numbers somewhere, and make it possible to see trends over time.

**Comment by matthewloring** [comment]
Reassigning to @ofrobots to investigate daily runs.

**Comment by matthewloring** [comment]
@ofrobots Does the current state of matthewloring/cloud-trace-performance satisfy this bug for now? We still need to expand testing to other frameworks but that can be tracked independently

**Comment by ofrobots** [comment]
Agree that this can be closed now.
