### ISSUE TITLE
Slow dependency install (grpc)

### ISSUE THREAD

**Issue by melalj** [GoogleCloudPlatform/cloud-trace-nodejs#351]
Everytime I run npm install, it takes a long time to install cloud-trace-nodejs due to the compilation of `[grpc] Success: "/MY_APP/node_modules/@google/cloud-trace/node_modules/@google-cloud/common/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote`

Any way to speed up this?

**Comment by matthewloring** [comment]
Unfortunately there is not currently a way to speed this up. We are in the process of removing the dependency (which was transitively introduced through `@google-cloud/common`).

**Comment by matthewloring** [comment]
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/359 fixes this issue, we expect it to be released soon.

**Comment by kjin** [comment]
Version 0.6.2 removed grpc as a dependency, so I'll go ahead and close this.
