### ISSUE TITLE
"grpc" was loaded before the trace agent was initialized.

### ISSUE THREAD

**Issue by melalj** [GoogleCloudPlatform/cloud-trace-nodejs#355]
I keep getting this error when I start my app.

```
ERROR:@google/cloud-trace: grpc tracing might not work as /MY_APP/node_modules/@google/cloud-trace/node_modules/@google-cloud/common/node_modules/grpc/src/node/index.js was loaded before the trace agent was initialized.
```

Which actually doesn't really make sense since grpc is part of the trace module... and it says that it wasn't loaded? 🤔

**Comment by matthewloring** [comment]
This is another side effect of the recent addition of grpc as a dependency of this module. This should be fixed once the dependency is dropped in the near future.

**Comment by ofrobots** [comment]
We hope to have this issue resolved next week, in the meanwhile you can install `@google/cloud-trace` at version `0.5.10` as a work-around (a few fixes are missing from that release however, specifically: #345, #346, #352).

**Comment by matthewloring** [comment]
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/359 fixes this issue, we expect it to be released soon.

**Comment by kjin** [comment]
Version 0.6.2 removed grpc as a dependency, so this message should not be showing up anymore. I'll close this, please re-open if it somehow still appears.
