### ISSUE TITLE
Loopback.js support

### ISSUE THREAD

**Issue by paulgoldbaum** [GoogleCloudPlatform/cloud-trace-nodejs#387]
I wanted to know if there are any plans to support loopback (http://loopback.io) in the short term. It uses express under the hood, so it should work right away but I haven't managed to get any traces.
If there's anything I can try out to provide you with more info I'll be happy to help.

**Comment by matthewloring** [comment]
We do not currently have plans for explicit support but I would have expected express tracing to work as you mentioned. Could you try running your app with the [`logLevel`](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v0.6.x/config.js#L22) configuration [option](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#configuration) set to 4 and sharing any output generated by the trace agent?

**Comment by paulgoldbaum** [comment]
Ok, so it looks like the patching is working correctly, here's the output:

 INFO :@google/cloud-trace: Locally provided ProjectId: -----
 INFO :@google/cloud-trace: Flushing: performing periodic flush
 INFO :@google/cloud-trace: trace agent activated
 INFO :@google/cloud-trace: Patching http at version v6.9.4
 INFO :@google/cloud-trace: Patching express at version 4.14.1
 INFO :@google/cloud-trace: Patching connect at version 3.4.1
 INFO :@google/cloud-trace: Patching mongodb-core at version 1.3.21
 INFO :@google/cloud-trace: Patching redis at version 2.6.5
 INFO :@google/cloud-trace: Flushing: performing periodic flush

The issue must be something else then. I'll run some tests with the debug output enabled and see if I can find anything. Thanks for the help!

**Comment by matthewloring** [comment]
Yup, that looks like good initialization output. If you get any additional output when you send requests to your server I can take a look and see if anything stands out.

**Comment by paulgoldbaum** [comment]
So, after creating tests projects for Loopback 2 and LB3 the good news is that Trace does indeed work with it out of the box. The bad news is that now I have to find where my app is messing up ;P

Here's the output of booting up the test app and hitting a model-based enpoint and a custom express endpoint, both tracing beatifully:
```
INFO:@google/cloud-trace: Locally provided ProjectId: maximal-record-121815
INFO:@google/cloud-trace: Flushing: performing periodic flush
INFO:@google/cloud-trace: trace agent activated
INFO:@google/cloud-trace: Patching http at version v6.9.5
INFO:@google/cloud-trace: Patching express at version 4.14.1
INFO:@google/cloud-trace: Patching connect at version 3.4.1
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
INFO:@google/cloud-trace: Writing root span
DEBUG:@google/cloud-trace: queued trace. new size: 1
INFO:@google/cloud-trace: Writing root span
DEBUG:@google/cloud-trace: queued trace. new size: 2
```

Thanks for the help, I'll close this as the problem is obviously not an issue with Trace!

**Comment by matthewloring** [comment]
Cool, feel free to reopen if anything else comes up!
