### ISSUE TITLE
Can't get gRPC Context Client to Server to match

### ISSUE THREAD

**Issue by ethanrubio** [GoogleCloudPlatform/cloud-trace-nodejs#434]
I'm trying to use this library to trace gRPC and Hapi requests throughout a small microservice environment.

There are three services (using a combo of gRPC and HapI) that I'm trying to log correctly in StackDriver Trace. I started all three services under the same project, but on StackDriver, I'm unable to link up the gRPC Client requests with the gRPC Server handling. However, a service with gRPC making HTTP requests to a Hapi server are correctly matched up on the web interface.

Any insights would be greatly appreciated! Thanks!

**Comment by matthewloring** [comment]
We currently propagate distributed context using an http header meaning that distributed tracing will only work over http for now. We are designing an alternate mechanism for grpc (likely using http://www.grpc.io/docs/guides/concepts.html#metadata) but need to coordinate between different language trace agents (we want to ensure a request sent from a Node.js grpc client to a go grpc server will handle context correctly).

**Comment by kjin** [comment]
I've opened #436 to address this by writing trace context to gRPC metadata. While this field isn't standardized for other Cloud Trace clients, it should provide distributed tracing for Node.js microservices.

**Comment by kjin** [comment]
Hi @ethanrubio, we just release version 1.0.1 which includes the PR mentioned above. Please give it a try when you have the time and feel free to re-open this issue if there are any problems!

**Comment by ethanrubio** [comment]
@kjin Thanks again for adding this! Is it possible to search for `x-cloud-trace-context` id in the web UI?

**Comment by matthewloring** [comment]
The value of `x-cloud-trace-context` has the form <trace_id>/<span_id>;o=<options>. It is possible to look up a trace from a trace id by navigating to `https://console.cloud.google.com/traces/traces?project=<your_project_name>&tid=<your_trace_id>`.
