### ISSUE TITLE
Tracing destroys proxied payload

### ISSUE THREAD

**Issue by rexxars** [GoogleCloudPlatform/cloud-trace-nodejs#437]
We've got an app that uses hapi with [h2o2](https://github.com/hapijs/h2o2) for proxying requests to a different service. When the trace agent is enabled, the responses seem to be empty. The response headers are included as expected, but there is no body.

I've made a reproducible test case here: https://github.com/rexxars/gtrace-proxy-issue

If I start the agent and disable *either* the `http` or the `hapi` instrumentation (or both), everything seems to work as expected.

**Comment by ofrobots** [comment]
@rexxars Thanks for the bug report. We are prototyping a fix on https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/438.

**Comment by matthewloring** [comment]
We will try to get a release out

**Comment by rexxars** [comment]
Awesome! Look forward to trying this out

**Comment by kjin** [comment]
Hi @rexxars, we just released version 1.0.1 which includes the PR above. Please give it a try and let us know by re-opening this if there are any outstanding issues!
