### ISSUE TITLE
Manually set service name and version

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/cloud-trace-nodejs#454]
Currently I can't find the options to send the right service name and revision to through the client and it's impossible to filter only traces for one microservice.

I guess this works out of the box in App Engine, but we're running in K8.

**Comment by matthewloring** [comment]
It is not currently possible to do this. We can add a mechanism for this to the config for the agent.

**Comment by kilianc** [comment]
@matthewloring that would be awesome.

**Comment by kjin** [comment]
@kilianc We've just released 1.0.4, which contains changes from #457.

Note that if the service name/version doesn't match an internally known entry, it won't show up in the Stackdriver Trace UI under the dropdown menu -- instead, you can use the "Request URI" box to filter by label (this is an undocumented feature). The format is space-delimited `key:value` pairs, and the label keys for the service name and version are:

- `serviceContext.service` (service name): `trace.cloud.google.com/gae/app/module`
- `serviceContext.version` (service version): `trace.cloud.google.com/gae/app/module_version`

Therefore, if your service name is `foo` and your version is `v2`, the search query to filter just traces for this service is:

`trace.cloud.google.com/gae/app/module:foo trace.cloud.google.com/gae/app/module_version:v2`

Issue #306 contains more information about this. Note that in this issue I wrote that a minor version is also required. I do not believe that to be the case today (I've been able to filter traces without supplying a minor version at all), but you can try setting the minor version to a dummy value like `'0'` if things don't work.

Please try it, and let us know if there are any outstanding issues with this and we will look into it!

**Comment by kjin** [comment]
Closing this, feel free to re-open if necessary!
