### ISSUE TITLE
Tracing by environment?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/cloud-trace-nodejs#455]
I'm curious if this is possible.  I have multiple clusters across the same GCP project that represent various CI environments along with the production environment.  Is there any way to have tracing break them out by k8s cluster?

![image](https://cloud.githubusercontent.com/assets/7675942/24478271/1c3b592c-148f-11e7-8ebc-00343c8e711d.png)

**Comment by matthewloring** [comment]
Would a way to specify service name and version be sufficient for this or is there another way you differentiate the clusters? (would https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/454 be a solution to the problem?)

**Comment by oshalygin** [comment]
@matthewloring yeah that would be awesome.  

Ideally when starting the agent one of the args would be "serviceName" and "version", that way I could set this via ENV variables on the running contain for each environment.  For instance.

`TRACE_APPLICATION_SERVICE=web`
`TRACE_APPLICATION_VERSION=1.3.3`


```javascript
require('@google-cloud/trace-agent').start({
  ignoreUrls: [
    '/_ah/health',
    '/healthz'
  ],
  serviceName: process.env.TRACE_APPLICATION_SERVICE,
  serviceVersion: process.env.TRACE_APPLICATION_VERSION
});

And my pod spec could look like this:

```yaml
spec:
      containers:
        - name: fe-web
          image: 'us.gcr.io/merchant-dash/merchant-dashboard:2.11.0'
          volumeMounts:
            - mountPath: /cache
              name: temp-volume
          env:
            - name: MONGO_IP
              valueFrom:
                secretKeyRef:
                  name: env-variables-secret
                  key: mongo_ip
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: env-variables-secret
                  key: mongo_port
            - name: TRACE_APPLICATION_SERVICE
              valueFrom:
                secretKeyRef:
                  name: env-variables-secret
                  key: trace_application
              - name: TRACE_APPLICATION_VERSION
              valueFrom:
                secretKeyRef:
                  name: env-variables-secret
                  key: trace_version
              - name: GCLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  name: env-variables-secret
                  key: gcloud_project
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
```

**Comment by kjin** [comment]
@oshalygin We've just released 1.0.4, which contains changes from #457.

Note that if the service name/version doesn't match an internally known entry, it won't show up in the Stackdriver Trace UI under the dropdown menu -- instead, you can use the "Request URI" box to filter by label (this is an undocumented feature). The format is space-delimited `key:value` pairs, and the label keys for the service name and version are:

- `serviceContext.service` (service name): `trace.cloud.google.com/gae/app/module`
- `serviceContext.version` (service version): `trace.cloud.google.com/gae/app/module_version`

Therefore, if your service name is `foo` and your version is `v2`, the search query to filter just traces for this service is:

`trace.cloud.google.com/gae/app/module:foo trace.cloud.google.com/gae/app/module_version:v2`

Issue #306 contains more information about this. Note that in this issue I wrote that a minor version is also required. I do not believe that to be the case today (I've been able to filter traces without supplying a minor version at all), but you can try setting the minor version to a dummy value like `'0'` if things don't work.

Please try it, and let us know if there are any outstanding issues with this and we will look into it!

**Comment by oshalygin** [comment]
@kjin badass, thanks! Going to roll this in later today!!

**Comment by matthewloring** [comment]
Closing this for now.
