### ISSUE TITLE
Arbitrarily pass time spent to endSpan

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/cloud-trace-nodejs#456]
We have a use case where we batch multiple calls to a database with a native batch API and in the response we get the `responseTime` for each individual call.

We are tracing how long that takes but we would like to track them singularly passing the number of milliseconds to endSpan or maybe some other method?

Thanks

cc/ @calufa

**Comment by kilianc** [comment]
This may be a little hacky but I think it will help understand what I am trying to do:

https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/trace-span.js#L48

```js
TraceSpan.prototype.close = function(endTime) {
  this.endTime = (new Date()).toISOString();
};
```

and

https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/trace-api.js#L53

```js
ChildSpan.prototype.endSpan = function(endTime) {
  this.span_.close(endTime);
};
```

This is just me looking how the calls are actually stacking up.

**Comment by kjin** [comment]
Hmm -- just to make sure I understand -- if you are batching database calls, would you create a span per call, or one span that represents all calls? In the latter case, how would you select which `responseTime` would be used to determine the length of that span?

**Comment by kilianc** [comment]
> would you create a span per call

Indeed, and then call `endSpan` on each one of them with the `responseTime` value.
