### ISSUE TITLE
Doesn't work with yarn?

### ISSUE THREAD

**Issue by tizmagik** [GoogleCloudPlatform/cloud-trace-nodejs#470]
Apologies if this is a bug with `yarn` and not with how this package is published, but I get the following error when trying to install with `yarn`:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@google-cloud%2ftrace-agent: User not found".
```

**Comment by ofrobots** [comment]
@tizmagik seems to be working for me. Which version of yarn are you using and how are you invoking it.

<details>
❯ yarn add @google-cloud/trace-agent
yarn add v0.20.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @google-cloud/trace-agent > gcp-metadata > retry-request > request > node-uuid@1.4.8: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 200 new dependencies.
├─ @google-cloud/common-grpc@0.3.2
├─ @google-cloud/common@0.12.2
├─ @google-cloud/logging@1.0.0
├─ @google-cloud/trace-agent@1.1.0
[...]
✨  Done in 3.81s.
</details>

**Comment by tizmagik** [comment]
The version i was using was 0.22, also just tried with latest 0.23.2

```
➜  temp yarn add @google-cloud/trace-agent
yarn add v0.23.2
[1/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@google-cloud%2ftrace-agent: User not found".
```

**Comment by tizmagik** [comment]
Ah, it was a local `.npmrc` problem, I had it to `always-auth=true` for our private npm registry. Apologies for the noise.
