### ISSUE TITLE
Tracing across pods/services in a cluster?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/cloud-trace-nodejs#492]
Anyone know the configuration necessary to orchestrate a Trace call that starts at the NodeJs application and traverses to another service, in GKE?

My NodeJs application(Express) lives in one pod and exposes a public API.  When the API is hit, the service handles the request and passed it down to other pods within the cluster that ultimately communicate with SQL/NoSQL DBs.  I'd like to be able to Trace the whole call from start to finish.

I'm wondering if this is performed by configuring the `service-context` ?

https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/config.js#L133

**Comment by matthewloring** [comment]
A description of our cross-service tracing functionality can be found [here](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/f8b74e6ec0af23adb531ff48aa18ad1d89703834/doc/trace-api.md#cross-service-trace-contexts). If both the public API and database pods are implemented in Node.js and use the trace agent then intermediate pods could propagate this header to achieve the desired tracing (note that sampling decisions made by the agent could still cause some spans not to show up). Are the intermediate pods/database interaction handled by Node.js?

**Comment by oshalygin** [comment]
@matthewloring unfortunately the pods/database interactions are not handled by NodeJs, instead they're Java services communicating with GCP CloudSQL and a MongoDB hosted under a GCE instance.

**Comment by matthewloring** [comment]
Ah ok, does control return to the Node.js service to respond to incoming user requests or is responding handled by another component of the system? You could look into instrumenting your Java applications using https://github.com/GoogleCloudPlatform/cloud-trace-java.

**Comment by oshalygin** [comment]
The response is handled by the same component(Node.js).  Going to look into instrumenting this on the Java side and see if this persists down, thanks @matthewloring !!

**Comment by oshalygin** [comment]
Closing for now until further research.  I'll document the findings in a few days 👍

**Comment by matthewloring** [comment]
Sounds good!
