### ISSUE TITLE
[Question] - How can I use cloud-trace to trace performance of functions

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/cloud-trace-nodejs#498]
I wanna trace how much time, CPU and other resources are being utilized by a specific function. These functions are not behind an API. After initializing them in my application, I am yet to see any trace reports for them. Is this supported? If so, how can I attain it? Thanks!

**Comment by matthewloring** [comment]
If the functions are not executed on behalf of incoming requests, you could use [`runInRootSpan`](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md#trace-spans) to gather wall time information. This should be a good approximation of CPU time assuming there is no blocking I/O in the function. However, if you are able to run the function locally, you may have better luck gathering CPU/memory usage using other profiling tools ([1](https://nodejs.org/en/docs/guides/simple-profiling/), [2](https://www.npmjs.com/package/v8-profiler), [3](https://nodejs.org/en/blog/uncategorized/profiling-node-js/)). What other resources are you interested in tracking?

**Comment by matthewloring** [comment]
@VikramTiwari Did you get a chance to try the custom span api or do you have more information about the resources you're interested in?

**Comment by VikramTiwari** [comment]
@matthewloring Thanks for the detailed comment. I am yet to try `runInRootSpan`. Read the associated link and seems like it should be the solve of what I am looking for.

Normally I would use `dtrace` or even chrome debugger for profiling. What I was looking for is the real-time, in the background method. The way `cloud-trace` works.

In general, I am trying to create a node package which you will require in your code and init. It will collect trace info on various functions in all the various parts of the code and then you can look at cloud console to understand how much time each individual function is taking. (too much to ask for? 🙏 )

**Comment by matthewloring** [comment]
One of the goals for this package is to keep the overhead low enough to be practical in production. `runInRootSpan` can give timing information at the per-function level but instrumenting too many functions will have a noticeable impact on performance.

**Comment by matthewloring** [comment]
I'm going to close this for now. You're welcome to re-open if you have any further questions.
