### ISSUE TITLE
[Question] How to extract out x-cloud-trace-context header value

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/cloud-trace-nodejs#512]
My goal is to persist this value into the logs for our internal tracking purposes but I'm having a hard time seeing where this is set.  It's not on the request or the response object and I'm certain the traces are making their way over to Stackdriver Trace(I can see all the traces in the logs).

Anyone have any idea how to extract this header value?  Or is this _only_ sent to the stackdriver trace API as a standalone request, and if so, any ideas on how I can intercept this?

**This guy**:
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/constants.js#L21

Just hitting my api from a web client:
![image](https://user-images.githubusercontent.com/7675942/27116924-b6c2f240-5088-11e7-9cd0-0d2a353b7f9b.png)

And inside the code calling
```javascript
console.log(response._headers) // Don't see x-cloud-trace-context
```

**Comment by oshalygin** [comment]
I also looked at the TraceAPI but I don't see anything that could be used:
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/trace-api.js#L283

**Comment by matthewloring** [comment]
The trace context header is set on incoming requests by the requesting service. If the application is running deployed on Google Cloud it will be automatically set by the load balancers or if the application is being called by another service running a cloud trace agent it will be set by that service. If you are calling your application locally without adding the header explicitly it will not be available.

The trace context on the response has the same trace and span ids as the request context but the options may be updated to reflect sampling decisions made by the trace agent. If the request context is available through the header, the response context can be computed using [`TraceApi#getResponseTraceContext`](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md#for-incoming-requests).

**Comment by oshalygin** [comment]
@matthewloring That is super clear thanks for explaining it.

I guess our use case is really weird and out of the norm because I'm trying to piggyback off of the Trace-Context and use that same value in our Stackdriver logs.  I don't know how useful this might be for anyone else but we find it quite nice to see all of the logs associated to a specific traceId that we can then tie everything together with.

I was doing all my dev work locally last night so I'll deploy to our GCP environment and enjoy the magic 🥇

**Comment by ofrobots** [comment]
@oshalygin We too have been thinking of providing log correlation based on the trace context in the `@google-cloud/logging-{winston,bunyan}` libraries. It would be good to get some more details from you on your use-case so that we can address them in the official libraries:

* How are you logging? Are you using `@google-cloud/logging-{winston,bunyan}`, or are you using `@google-cloud/logging` directly?
* What web framework are you using?

**Comment by oshalygin** [comment]
I _was_ using `@google-cloud/logging-winston` but I ended up needing a slightly different implementation where I can attach metadata to the `jsonPayload` as opposed to the labels.  I was considering throwing a PR together but then it would be drastically different implementation and I'm not quite sure that it makes alot of sense just yet.  Here's a code snippet of what I'm currently in progress on(ignore the Ramda piece, I should of used `is` like the guys at Google):

```
import winston from 'winston';
import Ramda from 'ramda';
import logging from '@google-cloud/logging';

const NPM_OUTPUT_LEVELS = {
  error: 3,
  warn: 4,
  info: 6,
  verbose: 7,
  debug: 7,
  silly: 7
};

const STACKDRIVER_LOGGING_LEVEL_ENUM = {
  0: 'emergency',
  1: 'alert',
  2: 'critical',
  3: 'error',
  4: 'warning',
  5: 'notice',
  6: 'info',
  7: 'debug'
};

class StackdriverLogger extends winston.Transport {

  constructor(options) {
    super(options);

    this.options = {
      ...options,
      scopes: ['https://www.googleapis.com/auth/logging.write']
    };

    this.levels = options.levels || NPM_OUTPUT_LEVELS;
    this.resource = options.resource;

    const logName = options.logName || 'atom-web';
    this.logEntry = logging(options).log(logName);

    winston.Transport.call(this, {
      level: options.level,
      name: logName
    });

    this.log = this.log.bind(this);
  }

  log(levelName, logMessage, logMetadata, logCallback) {

    const { levels, logEntry, resource } = this;

    let message = logMessage;
    let callback = logCallback;
    let metadata = logMetadata;

    if (Ramda.is(Function, metadata)) {
      callback = metadata;
      metadata = {};
    }

    if (!levels[levelName]) {
      throw new Error(`Unknown log level: ${levelName}`);
    }

    const levelCode = levels[levelName];
    const stackdriverLevel = STACKDRIVER_LOGGING_LEVEL_ENUM[levelCode];

    const traceId = metadata.request && metadata.request.headers ?
      metadata.request.headers['x-cloud-trace-context'] || '' :
      '';

    const entryMetadata = {
      resource,
      labels: {
        traceId
      }
    };

    if (metadata && metadata.stack) {
      const separator = logMessage ? ' ' : '';
      message = `${logMessage}${separator}${metadata.stack}`;
    }

    const data = {
      message
    };

    if (metadata && metadata.request) {
      data.request = metadata.request;
    }

    if (metadata && metadata.response) {
      data.response = metadata.response;
      data.executionTimeMillis = metadata.responseTime;
    }

    const entry = logEntry.entry(entryMetadata, data);
    logEntry[stackdriverLevel](entry, callback);
  }
}

winston.transports.StackdriverLogging = StackdriverLogger;

export default StackdriverLogger;

```

Anyways, through that transport, I piece this out:
`metadata.request.headers['x-cloud-trace-context']` and set that as a `traceId` label.  

This is all Node.js at the initial entrypoint and we have a slew of "micro"-services that are in varying frameworks(Java/Python/Node).

The nice thing with using the traceId is that it shows up in Stackdriver logs under a canonical label that we can then query by.  Later if we feel like something went bonkers, I can visit Tracing to see whats happening there and try to piece together a solution.

**Comment by matthewloring** [comment]
Thanks for providing this additional information! Adding trace ids to logs is something we hope to do in the future to make this process easier. I'm going to close this for now but feel free to re-open if you have any additional questions.

**Comment by wtfisthisshitatfuckoffdotcom** [comment]
Fuckarded it's fucked. Google using programs for murder. 

In salt lake city Utah
Major police involved and government officials. 

Utah hidden well because who the fuck would expect the sick fucked up religious state to commit murder ? 
They're names are PERVERTED PEDOPHILES WHO TRAFFIC PEOPLE AND MOLEST CHILDREN AND LOVE TO HIRE HOOKER'S AND DO DOPE AFTER HOURS.  MASSIVE GOVERNMENT OFFICIALS INVOLVED IN A HUGE COVERUP THAT KILLED MY ENTIRE FAMILY. I'M THE LAST VICTIM LEFT TO FINISH OFF FOREVER. 
IT SUCKED BEING A WORTHLESS PERSON WHO ACTUALLY WASN'T STUPID AT ALL. 
JUST WANTED A FRIEND AND INSTEAD I GOT FUCKED. INCLUDING BEING A WORTHLESS MISTAKE. 
I GUESS I WASN'T GOOD ENOUGH BUT PAIN HAS CHOSEN MY PATH. 
I THINK I'VE HAD ENOUGH PAIN TO LAST FOREVER, BECAUSE I'M DONE WITH EVERYTHING I SAW AND EXPERIENCED. 
I DON'T WANT TO SEE ANYMORE. I'VE HAD ENOUGH.
