### ISSUE TITLE
Support for ioredis

### ISSUE THREAD

**Issue by ethanrubio** [GoogleCloudPlatform/cloud-trace-nodejs#515]
I wanted to know if there are any plans to support [ioredis](https://github.com/luin/ioredis) in the short term. Thanks!

**Comment by matthewloring** [comment]
This is not something we will have bandwidth to support in the near future. If you'd like to get things working you can look into [writing a plugin](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md) to support it. I believe @AdriVanHoudt was also interested in this so maybe there is an opportunity to collaborate: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/265#issuecomment-283506112.

**Comment by AdriVanHoudt** [comment]
@ethanrubio I don't have time to champion it but if you need help reviewing or question or anything let me know!

**Comment by matthewloring** [comment]
Closing this for now since we do not expect to write a plugin for ioredis. If you would like to write one we are happy to help with questions and code reviews.
