### ISSUE TITLE
Merge into gcloud-node

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/cloud-trace-nodejs#52]
Hey guys, is there any plan to merge this with [gcloud-node] (https://github.com/GoogleCloudPlatform/gcloud-node) rather than a new library.

Also support for logging is required [gcloud-logging] (https://github.com/GoogleCloudPlatform/gcloud-node/issues/842)

**Comment by ofrobots** [comment]
This module is supposed to be automatic tracing agent. The idea is that you include the module and your application gets traced (express, mongo, outgoing http, etc.) without changes to the application code.

It is not an interface to talk to the Cloud Trace API, and as such the objectives are quite different from [gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node).

**Comment by VikramTiwari** [comment]
Oh wow! That's a great agenda. :+1: Any idea when can we expect any alpha release?

**Comment by ofrobots** [comment]
Hopefully very :soon:. Stay tuned.
