### ISSUE TITLE
Breaking change in 2.1.1

### ISSUE THREAD

**Issue by evanlucas** [GoogleCloudPlatform/cloud-trace-nodejs#527]
It looks like `require('@google-cloud/trace-agent').get().constants` no longer works the way it did in 2.1.0. `.get()` seems to return undefined now. Was that change on purpose?

**Comment by kjin** [comment]
It seems like I accidentally introduced a breaking change, as get() now only returns a `TraceAgent` object if the Trace Agent was started first. I will address this ASAP.

**Comment by evanlucas** [comment]
Thanks!

**Comment by ofrobots** [comment]
Fixed in v2.1.2.

**Comment by evanlucas** [comment]
Thanks for the quick fix!
