### ISSUE TITLE
Logger_ not correctly initialized when agent is started on disabled mode

### ISSUE THREAD

**Issue by jniemin** [GoogleCloudPlatform/cloud-trace-nodejs#535]
On latest version (2.1.2) if trace agent is started as disabled, `this.logger_` is not initialized properly in `src/trace-api.js`. 

Example code
```
const traceApi = traceAgent.start({
    enabled:false
});

const span = traceApi.createChildSpan({name:"myspan"})
```

This will fail with error

```
 TypeError: Cannot read property 'warn' of undefined
    at TraceAgent.createChildSpan (node_modules/@google-cloud/trace-agent/src/trace-api.js:200:17)
```

This used to work with 2.1.0

**Comment by kjin** [comment]
We have already fixed the issue on master. I will release 2.1.3 today to include the fix. Thanks for reporting this!

**Comment by kjin** [comment]
@jniemin 2.1.3 was just released, let us know if the problem persists!
