### ISSUE TITLE
Tracing might not work as the following modules were loaded before the trace agent was initialized: ["once","assert-plus","qs"]

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/cloud-trace-nodejs#540]
I am not sure where I am supposed to report this, feel free to close is this is the wrong place.

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2531

**Comment by kilianc** [comment]
@matthewloring thanks for the reply!

This behavior is a bit odd. I only use explicit tracing and I don't want any other probes intercepting my calls, how do I turn the warning off ?

Forget about `stderr` vs `stdout`, that was just a reminder that all those warning could potentially be ignored.

**Comment by kilianc** [comment]
Maybe I just figured it, I need to set false all the keys here https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/config.js#L35-L59 correct ?

What if there is a new plugin added, is there a way to get a list of active plugins and iterate over them ?

**Comment by matthewloring** [comment]
You are correct. Providing an alternate plugins object in your configuration with falsey values will disable specified plugins. However, the plugins currently provide automatic tracing and handle propagating the asynchronous context that allows us to associate child spans with root spans (https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#how-does-automatic-tracing-work). Just a heads up that disabling plugins may interfere with your ability to manually trace for this reason. Also, disabling the plugins will also not disable the message you are seeing. Maybe we should decrease its priority. We should also be able to provide an API for inspecting the currently supported/enabled plugins.

**Comment by ofrobots** [comment]
@kilianc depending on what exactly you are doing, there is also a low level API that lets you talk to the Tracing API directly: https://www.npmjs.com/package/googleapis. This might be a bit too low level though.

**Comment by kilianc** [comment]
@ofrobots I am ok writing our own middleware, we track traces anyway in logs, we just need the nice aggregated, plotted data and the alerts.

This is actually perfect for our use case, where we use cloud trace just as backend.

**Comment by ofrobots** [comment]
Alright, I'm going to close this issue in that case. Please re-open if I misunderstood, or if there is something more actionable here. Thanks!

**Comment by kilianc** [comment]
@ofrobots I started the work on this but I can't find the documentation for the trace api v2 which is used here: https://github.com/google/google-api-nodejs-client/blob/master/apis/cloudtrace/v2.ts#L29

What's a good place to start? I found a lot of code samples for v1 https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects/patchTraces

**Comment by kilianc** [comment]
I also see that this module itself [uses `v1`](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/trace-writer.js#L306) is this the version I should stick to?

**Comment by matthewloring** [comment]
As you found, most of the current documentation is around v1. It is in our backlog to migrate to v2 at some point but it is currently not a high priority and we expect v1 will be around for a while. v2 clarifies a few previously ambiguous cases (like how to report strings that have been truncated to save network bandwidth). If the lack of samples doesn't slow things down too much then it may be good to take advantage of the extra clarity in v2. Otherwise, v1 should work for you.

**Comment by kilianc** [comment]
@matthewloring gotcha. I'll stick to v1 for now, took me 5 minutes to have some working code just looking at the docs, I am pretty happy with it :)
