### ISSUE TITLE
Semver throws error while initializing trace agent

### ISSUE THREAD

**Issue by sanderploegsma** [GoogleCloudPlatform/cloud-trace-nodejs#545]
I tried adding the trace agent to an application running Node.js 8.1.4 and got this error thrown on startup. I'm not sure why the `version` field in the package.json would contain the resolved url instead of the version number, but as fair as I traced it correctly it would be fairly easy to avoid throwing by testing if `semver.valid()` on `trace-plugin-loader.js:103:41`

``` 
/app/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: https://registry.npmjs.org/redis/-/redis-2.7.1.tgz
    at new SemVer (/app/node_modules/semver/semver.js:293:11)
    at Range.test (/app/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/app/node_modules/semver/semver.js:1085:16)
    at /app/node_modules/@google-cloud/trace-agent/src/trace-plugin-loader.js:103:41
    at Array.forEach (native)
    at loadAndPatch (/app/node_modules/@google-cloud/trace-agent/src/trace-plugin-loader.js:102:16)
    at Function.Module_load [as _load] (/app/node_modules/@google-cloud/trace-agent/src/trace-plugin-loader.js:159:27)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/src/app.js:4:15)
```

**Comment by matthewloring** [comment]
It looks like the npm documentation requires the `version` field of package.json to be parsable by `semver` (https://docs.npmjs.com/files/package.json#version). Is the version being set manually or by some other tool? I agree that we shouldn't crash here though and can add such a check. However, if we are not able to parse the version then we will not be able to provide any redis tracing.

**Comment by sanderploegsma** [comment]
The only place I can find the url is in my `package-lock.json`. Maybe it has something to do with https://github.com/npm/npm/issues/15050?

> However, if we are not able to parse the version then we will not be able to provide any redis tracing.

Right, I expected this would be the case. I just figured starting without tracing is better than crashing the process 👍

**Comment by sanderploegsma** [comment]
For future reference, I found out this behaviour was triggered by https://github.com/npm/npm/issues/16926. Looks like npm@5.0.x is very much unstable.
