### ISSUE TITLE
Test for memory leaks

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-trace-nodejs#55]
Ran the [Bookshelf example app](https://cloud.google.com/nodejs/getting-started/tutorial-app?hl=en) and put load on it with ``ab -n 1000000 -c 20 "${url}?pageToken=333"``.  It stabilized at 100% cpu usage and 400MB (1.21%) of RAM.

@ofrobots How does this look?

**Comment by matthewloring** [comment]
Took ~10,000 requests to reach stable memory usage.

**Comment by matthewloring** [comment]
Resource stats were gathered using ``docker stats``.

**Comment by ofrobots** [comment]
Is it possible to automate the test? Can we run the test overnight and plot memory consumption across. Did you verify that the traces being captured and publish to the Trace API?

**Comment by matthewloring** [comment]
![memory](https://cloud.githubusercontent.com/assets/1485909/9673378/8dfb1c28-5258-11e5-8d1c-5cee244a9733.jpg)

The test is automated and I did verify that traces were being published. Note: that lower access should read operations instead of time. It looks pretty stable from a distance (but that doesn't rule out a small leak).
