### ISSUE TITLE
Where is mongoose plugin described in README?

### ISSUE THREAD

**Issue by ivanseidel** [GoogleCloudPlatform/cloud-trace-nodejs#565]
Readme states that `mongoose` is a supported plugin, however, it is not contained inside the `src/plugins` folder. Did I miss something?

**Comment by matthewloring** [comment]
`mongoose` tracing is provided by the `mongodb-core` plugin.

**Comment by ivanseidel** [comment]
Should `find` calls be tagged as well, or just write/cursors?

**Comment by kjin** [comment]
Yes, `find` calls should be traced (I assume you meant traced instead of tagged).

**Comment by ofrobots** [comment]
I am closing this issue, as I believe it has been answered. Please add a comment if that is not the case.
