### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-trace-nodejs#566]
The next version of hapijs (v17) will be async/await only. Is this supported by this tracing module?

**Comment by matthewloring** [comment]
The hope is that async hooks (introduced in https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/commit/0e15b6c95dd019787540aa31c9c889028abc708c) will work with async/await. It can be enabled by setting the `GCLOUD_TRACE_NEW_CONTEXT` environment variable.  If you're experimenting with hapi@17 we'd be interested to hear how the async hooks based tracking works for you.

**Comment by AdriVanHoudt** [comment]
On node 8 it will async hooks by default no?

**Comment by matthewloring** [comment]
Not yet, we're still hoping to get some feedback on how it works in the wild before enabling it by default. If you're able to try it out with your uses of the trace agent we would be really interested to hear how it goes!

**Comment by AdriVanHoudt** [comment]
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/commit/0e15b6c95dd019787540aa31c9c889028abc708c#diff-168726dbe96b3ce427e7fedce31bb0bcR23 does that no or am I misreading?

**Comment by matthewloring** [comment]
That condition will only be true if we are running on a node version >= 8 and the `GCLOUD_TRACE_NEW_CONTEXT` environment variable is set.

**Comment by AdriVanHoudt** [comment]
Ok totally misread that :D

Do you have an eta on when it will become the default?

**Comment by ofrobots** [comment]
At this point we are looking to get feedback from real world use-cases before enabling `async-hooks` by default. It would be really awesome if you could give it a shot with v2.2.0+ and report back 💯.

Once we have some confidence that this is working reasonably, we can make this the default behaviour for Node 8+.

**Comment by ofrobots** [comment]
Ping @gauravkul, based on https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/502#issuecomment-323732452, it seems like you might also be using code depending on un-transpiled async/await. If you are willing to try out the latest `async-hooks` based support and report back, that would be awesome!

**Comment by AdriVanHoudt** [comment]
When hapi 17 is out and 8 is in lts we will start to switch to those and I can test real world cases. If hapi 17 is released before 8 lts we can do some testing up front and probably add 17 to the test suite here with node 8 and async hooks enabled

**Comment by istraub** [comment]
So I stumbled on this thread last night, as we recently injected some async/await usage into a project and tracing that had been working went away...  Our containers (running in GKE) were already running node 8.6, so I quickly redeployed into our QA environment with the GCLOUD_TRACE_NEW_CONTEXT env set and whoot, we have trace details again....  Not sure if you are still needing feedback before rolling this out as default behavior, but so far so good for us.  We are running a consistent amount of traffic through our services with an eye on tracing our Spanner DB interaction, and it's all working as expected thus far.

**Comment by kjin** [comment]
@istraub Glad to hear that! At this point feedback like this is super valuable to us, so thank you for your input!

**Comment by ofrobots** [comment]
@AdriVanHoudt we're wondering if you have had a chance to experiment with the async-await support in this library now that hapi17 is also out. Before enabling by default, we want to ensure we have as much real world feedback as possible.

**Comment by AdriVanHoudt** [comment]
Not yet sorry, I will probably have time by the end of the year to really experiment, deadlines and such :D

**Comment by kjin** [comment]
@ofrobots hapi 17 doesn't work out of the box, I need to add support for it. I'll open a separate issue to track this.
