### ISSUE TITLE
Restify 6 support

### ISSUE THREAD

**Issue by xK0ff33** [GoogleCloudPlatform/cloud-trace-nodejs#571]
Is latest version of Restify supported? I'm trying to get it to work without success.

Not sure if it's because of using async/await (#566) in my code or some incompatibility with Restify.

**Comment by kjin** [comment]
We currently support up to v4 only. I'll look into what's changed in Restify 6 (and 5) and update our Restify implementation... thanks for bringing this to our attention!

Assuming you've followed the direction of `GCLOUD_TRACE_NEW_CONTEXT` in the other thread, I wouldn't expect usage of async/await to have an impact on database traces, but if you are observing other issues that you think might be cropping up from it please don't hesitate to file another issue.

**Comment by kjin** [comment]
Restify 5 and 6 seem to pass our unit tests fine, so it might in fact be the usage of async/await. Would you mind sharing a small repro of the issue?

**Comment by xK0ff33** [comment]
Sorry, turns out the problem is on my side - Stackdriver Trace is disabled in my cluster.
Do you possibly know if there is an option to enable it without recreating the whole cluster?

**Comment by kjin** [comment]
As far as I know, there isn't a way to enable it without recreating the cluster.

That being said, I believe our Trace Agent superficially doesn't patch Restify 5/6 yet... I'll try to get a fix in ASAP.

**Comment by kjin** [comment]
We're aiming to release the next version within the next week, in the meantime -- I would suggest copying [this file](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v2.2.0/src/plugins/plugin-restify.js) to your local directory, changing `SUPPORTED_VERSIONS` to `'<=6.x'`, and specifying the custom path to your local `plugin-restify.js` copy as follows:

`require('@google-cloud/trace-agent`).start({
  plugins: {
    restify: path.join(__dirname, 'path/to/plugin-restify.js') // absolute path
  }
})`

**Comment by kjin** [comment]
We've expanded the restify supported semver range to <=6 in the new release (v2.3.0)... please give it a try and re-open this issue if there are any problems.

We'd also greatly appreciate feedback on `GCLOUD_TRACE_NEW_CONTEXT` (from #566) if you are using it!
