### ISSUE TITLE
Improve docs on ignoreUrls option

### ISSUE THREAD

**Issue by amsibamsi** [GoogleCloudPlatform/cloud-trace-nodejs#574]
Found it confusing to know how the ignoreUrls option exactly works. From my limited understanding of the source it does do string matching, so specifying '/' will actually ignore all URLs. So exact matches need to be regular expressions, like /^\/$/. Can you please verify if this is how it works and then maybe add more detailed docs?

**Comment by kjin** [comment]
Yes -- each input string in `ignoreUrls` is treated as a regex against which the potentially ignored URLs will be matched, so '/' will end up ignoring everything. (In addition -- the URL is _also_ ignored if it's an exact match of an `ignoreUrls` element -- something we will remove as a semver-major change in the future.)

I'll change the docs to make it more reflective of its function. Thanks for bringing this to our attention!

**Comment by kjin** [comment]
I've updated the contents of `config.ts` to better describe `ignoreUrls`.

**Comment by amsibamsi** [comment]
Thanks a lot!
