### ISSUE TITLE
koa async await child spans not working

### ISSUE THREAD

**Issue by codyzu** [GoogleCloudPlatform/cloud-trace-nodejs#593]
We just activated this in our project and we have 1 root span per request and no child spans in our trace... resulting in 1 span for an entire request.

I did some debugging to attempt to understand the problem by using the `traceApi` to create a child span in our first koa middleware. The result is always null (this is the same result the `pg` plugin gives). Enabling the logLevel 4, I see:
* `WARN:@google-cloud/trace-agent: Custom Span API: Attempted to create child span without root`
* `WARN:@google-cloud/trace-agent: pg: Attempted to create child span without root`

We **do** use native `async/await` and no babel transpiling. I am running with `GCLOUD_TRACE_NEW_CONTEXT=1`. I confirmed the `cls-ah.js` module is being loaded (indicating the `GCLOUD_TRACE_NEW_CONTEXT=1`) is working.

It seems the `async_hooks` stuff is not working in our case.

Our current setup:
* `node v8.9.1` (also tested with v8.9.1)
* `koa@v2.3.4`
* `@google-cloud/trace-agent@2.3.1`
* `pg@6.4.2`
* __no babel, only native js__

Any ideas what else might be wrong? What to try???

**Comment by kjin** [comment]
I was able to reproduce this -- this is a bug in our code. Thanks for bringing this to our attention, I'm opening a PR to fix this shortly.

**Comment by codyzu** [comment]
Excellent! I spent some time trying to understand the bug to try to give you a better report. I did not determine if the issue is in the koa plugin or in `cls-ah.js`. It seems to change the context after setting the root span, but before calling the first middleware (more or less "undoing" the `api.wrap` call). 

Let me know if I can do something to help. Thanks!

**Comment by kjin** [comment]
@codyzu I just released 2.3.2, please give it a try. Any feedback on how well it works for you (especially revolving around the `GCLOUD_TRACE_NEW_CONTEXT` environmental variable) would be very helpful for us, so please don't hesitate to file additional issues if they come up.

Just as a fore-warning, while I investigating this I found that tracing koa 2 + got 7 might yield strange results (I think it's related to https://github.com/sindresorhus/got/issues/388). I know you didn't specify this as part of your stack... but just in case.

**Comment by codyzu** [comment]
Great! This is now working for us (and super insightful). We use `request-promise` rather than `got`, so it looks good for now.
