### ISSUE TITLE
Adding trace agent uses all of heap

### ISSUE THREAD

**Issue by caseyduquettesc** [GoogleCloudPlatform/cloud-trace-nodejs#603]
trace-agent is the only package using "lodash.merge"

I'm using node 8.9.1, latest trace agent, running on appengine flex env.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 
      3: baseClone ... 
      2: set(aka mapCacheSet) [/app/node_modules/lodash.merge/index.js:~713] [pc=0x3867669eb473](this=0x69a3b6bd381 <MapCache map = 0x19be35f40529>,key=0x16d9a2750109 <JSArray[2]>,value=0x840806f5d89 <JSArray[2]>) 
      1: set [native collection.js:~149] [pc=0x3867666395e7](this=0x69a3b6bd4b9 <Map map = 0x192b418848d9>,o=0x16d9a2750109 <JSArray[2]>,value=0x840806f5d89 <JSArray[2]>)
 
Security context: 0x38a771425ec1 <JSObject>
 ==== JS stack trace =========================================
<--- JS stacktrace --->
[27:0x34bb040]   711432 ms: Mark-sweep 1402.4 (1436.1) -> 1402.4 (1436.1) MB, 1608.6 / 0.0 ms  last resort GC in old space requested
[27:0x34bb040]   709824 ms: Mark-sweep 1402.4 (1467.1) -> 1402.4 (1436.1) MB, 1554.7 / 0.0 ms  last resort GC in old space requested
[27:0x34bb040]   708269 ms: Mark-sweep 1402.7 (1467.1) -> 1402.4 (1467.1) MB, 1786.4 / 0.0 ms  allocation failure GC in old space requested
<--- Last few GCs --->
 ```

**Comment by kjin** [comment]
We only use `lodash.merge` in http tracing, where we copy the request options object. We don't keep a handle to this object.

I'm not extremely familiar with out-of-memory errors, but playing around with object allocations locally, I found that the place where the heap runs out of memory is sensitive to the program structure and amount of memory given to the Node process in the first place. For example, this toy code

```js
const merge = require('lodash.merge');
const obj = [{}];
for (let i = 0; i < 10000000000; i++) {
  obj.push(merge(obj[i], { [i]: '' }));
}
```

runs out of memory either in the call to `merge` or `push` depending on how much memory is allowed for the process in the first place (adjusted by the `--max_old_space_size` flag). This suggests that the function that caused the out-of-memory error may not necessarily be the one causing a memory leak.

It's certainly possible that we cause a leak in a different part of our module, or the inclusion of the Trace Agent accelerates the gain towards running out of memory in an application that is already leaking memory elsewhere, but I believe this specific call to `lodash.merge` is not the culprit. I'd be glad to dig into it more if you can provide additional details (such as other modules you are using, or a heap dump).

**Comment by caseyduquettesc** [comment]
We are definitely leaking memory already :) But it's never the heap that fails, we have 4GB VMs and the process runs fine up until that 4GB and then appengine restarts the VM. We have never seen a limit of 1.5GB before we installed this module and never have seen a heap out of memory error, even when we do "run out of memory". I suspect appengine somehow sees us approaching the VM limit and restarts it.

It sounds possible that the module has accelerated the memory growth, but it's odd to me that it's the first time I've seen it run  out of heap space.

I'm not blaming the module for my memory problems, but I was hoping it could help diagnose my existing latency issues. It's just hard to diagnose a problem when the tool exacerbates it haha. It worked great for 15 minutes though, so wasn't totally fruitless.

We're using Restify 4.3 to run an API that hits cloud sql. Maybe you could dig into what lodash.merge is being used to merge? Maybe it has a circular reference or something?

**Comment by ofrobots** [comment]
>  if you can provide additional details (such as other modules you are using, or a heap dump).

Just a quick note, please don't post a heap-dump publicly, as it will likely contain sensitive information from your app.

**Comment by kjin** [comment]
@caseyduquettesc Does your app make a sizable number outgoing HTTP requests? The HTTP tracing plugin is the only place in the Trace Agent using `lodash.merge`: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/10ed0edb74f993f45b095de33a224376931fd88c/src/plugins/plugin-http.ts#L65-L71 I wouldn't expect an HTTP options object to have circular references, but either way, `lodash.merge` is capable of detecting this (if it didn't, that would be a much bigger problem).

Another question - is the out-of-memory error in `lodash.merge` reproducible? I'd expect that since the error only reports the last allocation attempt, that the allocation site would vary widely depending on network patterns. If I run a toy app that only makes outgoing http requests in a `setInterval`, the last allocation can occur anywhere.

**Comment by caseyduquettesc** [comment]
I suppose you could say we make a high number of outgoing http requests, there's at least two per incoming request, one to fetch access token info, and another to an internal authorization service. There's a third outgoing request that we sort of proxy, so that could potentially be a large request, some high outliers are around 100KB, but the average is closer to 200B.

I've tried running a version of the service that includes the trace agent four times, and each of those times the allocation error originated from the same spot, lodash.merge. At that point, I gave up trying to work around it. The crash would always happen within an hour of starting, so I'm pretty sure I could reproduce it.

Going back to that "sort of proxy" request we make, I never see these requests in my trace dashboard. Now, I admit I don't know much about how this agent works, but is it possible that the request is getting traced and buffered in some queue, but is never sent to the trace api? What's unique about this request is we save all the information needed to execute it into a PubSub event, and execute the request through a PubSub handler (in the same app). Could that affect anything?

All our our external http requests are made with [request-promise](https://github.com/request/request-promise).

Also, I just remembered that I used the trace agent last March or April in this app and did not have this issue. Tracing was noticeably less precise than this version.

**Comment by vmarchaud** [comment]
Don't know if related but i add kinda the same issue with a forked version of the agent (which do not modify the plugins or the API itself), i reproduced a leak when i used `request` to made 3rd party http calls inside a middleware (i might have few heapdumps around if you want), and for a unknown reason it doesn't leak with the core `http` client.

**Comment by kjin** [comment]
@caseyduquettesc @vmarchaud Thanks for the info -- I haven't tried using request-like libraries with the Trace Agent in looking into this issue. I'll try it and get back to you shortly.

**Comment by ofrobots** [comment]
@caseyduquettesc If you're using Node 6 or 8, there is a new low-overhead heap profiler you can use: https://www.npmjs.com/package/heap-profile. Would it be possible to run with this profiler (for a couple of hours) and see if the profiles show the leak and the cause.

The generated profiles contain stack traces, but no contents of the objects themselves, so these are more suitable for sharing.

**Comment by ofrobots** [comment]
Folks, a repro, heap profiles or heap dumps would be nice in helping us understanding the issue. If there is any more info, please share.

**Comment by vmarchaud** [comment]
That was the sample i wrote at the time that reproduced the leak (already 6 month old), dunno if it still happen with the current version : 

```javascript
require('.').start()
const express = require('express');
const request = require("request");
const app = express();

const handleRequest = (req, res) => {
  let _req = request('http://google.fr', (response) => {
    if (!response) return res.send(500)
    response.pipe(res);
  });
  _req.end();
};

const handleRequestWithCoreHttp = (req, res) => {
  const options = {
    hostname: 'www.google.com',
  };
  const _req = http.request(options, (response) => {
    response.pipe(res)
  });
  _req.end();
};


app.get('/', handleRequest);
app.get('/noLeak', handleRequestWithCoreHttp);
app.listen(8080, _ => console.log('Listening'))
```
If i put load on the `/` endpoint like this : 
`wrk -c 100 -t 2 -d 10 http://localhost:8080/`

My process take up to 600M of RAM after few seconds and the GC doesn't clear up some objects
Then if i put the load on the `/noLeak` endpoint, i got at maximum 90M of RAM used (with command : `wrk -c 100 -t 2 -d 10 http://localhost:8080/`)

`wrk` is just a simple binary that load test the endpoint with `GET` request, if you want to install it the name of the package is `wrk-node`

**Comment by ofrobots** [comment]
@vmarchaud Thanks! I believe there is a flaw in your test case. The default handler is making requests but the callback signature is wrong. This means that all outgoing request streams have nothing reading from them, which would leak memory. I am including a correct handler functions below.

With the copy of the code as you provided, here's what the memory usage looks like after a few minutes of load:

![image](https://user-images.githubusercontent.com/79017/34544196-cd0ca71a-f099-11e7-992d-b57de101077c.png)

If we fix the handler function to be the following:

```js
const handleRequest = (req, res) => {
  request(`http://www.google.com`).pipe(res);
};
```

The resulting memory usage looks like the following:

![image](https://user-images.githubusercontent.com/79017/34544174-95633112-f099-11e7-9a81-eeb3c21ea629.png)

I do not believe this is an issue in the trace library.

**Comment by baronfel** [comment]
I think I'm running into an issue around ever-growing heap as well after upgrading from 2.3.1 to 2.3.3.  

I'm running an Express API on Google Kubernetes Engine running k8s 1.6.11.
The Node version is 8.9
I'm using Express/Redis/MySQL trace agents.

I've got heap snapshots showing a `Trace` object with a `spans` array containing 286k spans in it after a couple days of continuous use.

After reverting back to 2.3.1 and letting it run for several hours, taking snapshots every hour, the size of the arrays of spans stays relatively constant.

What kind of data can I get to you to help diagnose?  My heap snapshots are from production and quite large (~400Mb), plus they have sensitive data in them, so I don't want to just upload them somewhere.

2.3.2:
![image](https://user-images.githubusercontent.com/573979/34578611-38174702-f14b-11e7-92bc-c309ae198e61.png)

2.3.1:
![image](https://user-images.githubusercontent.com/573979/34578626-4ac7a4be-f14b-11e7-87dc-31a3431e6acd.png)

**Comment by ofrobots** [comment]
@baronfel thanks! that is useful info, and sounds like a problem. Thanks for narrowing down the version range. Can you clarify one thing: earlier in your comment you mention 2.3.3 but later you show a screenshot with 2.3.2. I am guessing one of these is a typo. Is 2.3.2 the first version you see a regression with?

**Comment by baronfel** [comment]
My mistake, I typoed. 2.3.3 definitely showed the regression, and the heap snapshot is from that version. I'm hypothesizing the problem was introduced in 2.3.2 because of the change to how 'http' was wrapped. No strong suggestions, just a guy feeling. 2.3.3 looked comparatively minor in comparison.

**Comment by ofrobots** [comment]
@baronfel thanks! Yeah, 2.3.3 is relatively minor.  A few more questions: you mentioned that you are using Node 8.9. Which one precisely between 8.9.0 - 8.9.4?

My theory is that somehow there is context loss. As a result of that all your RPCs *appear* to correspond to an incorrect request. To confirm this theory, can you run with the `logLevel` raised to 2 or above. See 
https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/9866d292a5d5d8c01b02087246020ce663fa19ef/src/config.ts#L24-L28

I am wondering if you see lots of these warnings: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/9866d292a5d5d8c01b02087246020ce663fa19ef/src/trace-api.ts#L220-L222

**Comment by baronfel** [comment]
Sorry again, I was wrong on the node version. It's 8.8.11. Also updated the comment to reflect that.  I can see about raising the logging level, but we're sorta in an OMG MAKE IT WORK mode :)  I should be able to try the log level thing later today.

**Comment by baronfel** [comment]
> ` this.pluginName + ': creating child for an already closed span', `

That's an interesting observation: I haven't changed the logLevel yet, but I'm looking at all these stored spans and all of the first 100 belong to the same parentSpanId, despite being a) all `mysql` traces and  b) across more than an hour span.

**Comment by baronfel** [comment]
That's exactly the case, @ofrobots!

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/573979/34581476-1e6c21aa-f156-11e7-971d-8102b043b142.png">

I'm seeing that log message all over my updated app, running 2.3.3.

**Comment by ofrobots** [comment]
I've implemented a mitigation in https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/631. We can hopefully get this released soon. The issue still to be investigated is what is causing context confusion in your app in the first place (I'm extracting this into a standalone issue: #632). We'll be looking at the delta in 2.3.2 in detail to see if can figure this out completely from the code. Otherwise, we may need ask for some more data from your side.

Thanks a lot for the detailed report and for running the experiments!
