### ISSUE TITLE
Some spans are being incorrectly nested

### ISSUE THREAD

**Issue by evanlucas** [GoogleCloudPlatform/cloud-trace-nodejs#606]
Versions:

* node: `v8.9.1`
* trace-agent: `v2.3.0`

We are currently using the async_hooks based tracing and are occasionally getting mixed spans.
We have a custom implemented tracing plugin for couchbase and have a normal progression that contains 4 different operations (getAndLock, update, insert, replace) for this endpoint. They generally are all associated with the same http request. 

Normally, the trace list looks like this:
```
/route_name
    getAndLock
    update
        insert
        replace
```

When this issue occurs the trace list is very long and looks like:

```
/route_name
    getAndLock
    update
        insert
        insert
        insert
        unlock
        insert
        insert
        ... nested spans continue
```

I understand that this does not really give any reasonable information to aid with debugging
but, we currently use our same couchbase tracing plugin with the continuation-local-storage tracing
and do not see this problem. This is only occurring in a service that we just recently switched to async/await and switched over to using the async_hooks based tracing.

I'm still trying to come up with a reproducible test case in the time being, but wanted to get this
on yalls radar.

Thanks!

**Comment by kjin** [comment]
Thanks for reporting this -- please keep us updated when you discover a reproducible scenario!

**Comment by ofrobots** [comment]
We're trying some applications of our own as well, but if anyone has a repro is available, that would be quite helpful. Thanks!

**Comment by kjin** [comment]
Hi @evanlucas -- I'm closing this for housekeeping purposes. Please let us know if there is any additional info and I can re-open. Thanks!
