### ISSUE TITLE
Let users provide Project Id via GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/cloud-trace-nodejs#638]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2787

<a href="/JustinBeckwith"><img src="https://avatars2.githubusercontent.com/u/534619?s=88&v=4" height=44 width=44 align=left></a>@JustinBeckwith<br>January 8, 2018 9:58 PM

Today in cloudcats I am providing the ProjectId via the PROJECT_ID env var.  I also have to provide a keyfile, which I was passing into the code.  In an effort to make things a little more smooth on the config side,  I tried to use GOOGLE_APPLICATION_CREDENTIALS instead of defining PROJECT_ID and the keyfile.  The projectId is inside of my keyfile - but we still seem to require the ProjectId along with the key file :(

```
beckwith-macbookpro:web beckwith$ npm start

> cloudcats-web@1.0.0 start /Users/beckwith/Code/cloudcats/web
> GOOGLE_APPLICATION_CREDENTIALS=keyfile.json node server.js

info: Server running at: http://0.0.0.0:8080
ERROR:@google-cloud/trace-agent: Unable to acquire the project number from metadata service. Please provide a valid project number as an env. variable, or through config.projectId passed to start(). Error: getaddrinfo ENOTFOUND metadata.google.internal metadata.google.internal:80
ERROR:@google-cloud/debug-agent: The project ID could not be determined: getaddrinfo ENOTFOUND metadata.google.internal metadata.google.internal:80
```

Can we just read the projectId from the keyfile?

**Comment by stephenplusplus** [comment]
###### _January 8, 2018 10:02 PM_

We should already be doing that (via google-auth-library). I’m not sure of the code path that is throwing those errors— looks like trace-agent is unable to find the ID. I can dig in, but quick long to @ofrobots in case he knows what might be going on.

**Comment by stephenplusplus** [comment]
<a href="/ofrobots"><img src="https://avatars2.githubusercontent.com/u/79017?s=88&v=4" height=44 width=44 align=left></a>@ofrobots<br>January 8, 2018 11:22 PM

@JustinBeckwith do you mind opening the issue against https://github.com/GoogleCloudPlatform/cloud-trace-nodejs? It seems that the logic is missing from there.

**Comment by kjin** [comment]
Despite what google-auth-library does we are also storing the project ID for our own purposes as well, so it makes sense that this doesn't work. I'll look into it

**Comment by kjin** [comment]
How's this for an order of precedence when it comes to Project IDs:

1. `process.env.GCLOUD_PROJECT`
1. `traceConfig.projectId`
1. `traceConfig.credentials.project_id` [1]
1. `fs.readFileSync(traceConfig.keyFile).project_id` [1] [2]
1. `fs.readFileSync(process.env.GOOGLE_APPLICATION_CREDENTIALS).project_id`[3]
1. `fs.readFileSync(WELL_KNOWN_ADC_LOCATION).project_id` [4]
1. from metadata service

[1] Assuming that if the file pointed by `GOOGLE_APPLICATION_CREDENTIALS` can have project_id, so can a JSON object referenced by the trace agent config
[2] google-auto-auth gives precedence to [`credentials` over `keyFile`](https://github.com/stephenplusplus/google-auto-auth/blob/252db3e3226aefa7c3d9f7dce0575e968837f618/index.js#L88-L110)
[3] google-auto-auth gives precedence to [`credentials` and `keyFile` over application default credentials](https://github.com/stephenplusplus/google-auto-auth/blob/252db3e3226aefa7c3d9f7dce0575e968837f618/index.js#L88-L110)
[4] google-auth-library gives precedence to [env var over well-known location](https://github.com/google/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L192-L206)

This is beginning to make me think that the auth library (if it doesn't already) should expose this information (promise containing value of project ID). However, it seems like the [auth library doesn't do metadata service yet](https://github.com/google/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L116).

**Comment by ofrobots** [comment]
The comment you linked to in the last sentence seems out of date with the code. See https://github.com/google/google-auth-library-nodejs/blob/771bc6cdcf56f7d5e0b3a754c28190476251d6f6/src/auth/googleauth.ts#L571
