### ISSUE TITLE
Seeing performance issues with higher outbound http client requests

### ISSUE THREAD

**Issue by evanlucas** [GoogleCloudPlatform/cloud-trace-nodejs#639]
This is on node 8.9.4 and `@google-cloud/trace-agent@2.3.3`

7.2% seems a bit high to me?

The top of the JavaScript portion of the cpu profile looks like this:

```
[JavaScript]:
   ticks  total  nonlib   name
   3887    9.8%   10.0%  Builtin: KeyedLoadIC_Megamorphic
   3206    8.1%    8.2%  Builtin: KeyedStoreIC_Megamorphic
   2876    7.2%    7.4%  LazyCompile: *<anonymous> /opt/app/node_modules/lodash.merge/index.js:973:37
```

I'm *thinking* it is coming from https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/38d4673e433bc1ae156bf9d962c767ca0703ef7f/src/plugins/plugin-http.ts#L68 but could be wrong. I don't have it narrowed down to a reproducible test case yet, but I'm working on that now.

**Comment by ofrobots** [comment]
Thanks for reporting the issue – we'll take a look. Is there any chance for you to try 2.4.0?

**Comment by evanlucas** [comment]
Thanks for the quick response @ofrobots! I'll try 2.4.0 either tonight or tomorrow. I also just tried disabling the agent and performance *immediately* is no longer an issue. That could be due to a lot of other things though, so I'll try 2.4.0 and report back

**Comment by evanlucas** [comment]
I should have probably noted also that we are using the environment variable to use async_hooks as for context propagation as well, so some of the performance issues could be stemming from that as well.
