### ISSUE TITLE
HTTP/2 client tracing doesn't work in Node 9.4

### ISSUE THREAD

**Issue by kjin** [GoogleCloudPlatform/cloud-trace-nodejs#644]
Breaking changes in http2 module: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V9.md#9.4.0

EDIT: As @jinwoo pointed out, it actually does and it's only the test that's failing.

**Comment by kjin** [comment]
@jinwoo FYI

**Comment by jinwoo** [comment]
@kjin Do you know exactly which change broke this? Is it https://github.com/nodejs/node/pull/17406?

**Comment by kjin** [comment]
Yep -- seems like this exactly: https://github.com/nodejs/node/pull/17406/files#diff-696b2cc418addca5f3fe5020058f8b15L1406

Example of failing change: https://circleci.com/gh/GoogleCloudPlatform/cloud-trace-nodejs/1275

**Comment by jinwoo** [comment]
Could be just a testing problem. `rstWithInternalError()` is used from one of the tests: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/182c0cbc6fe7990c2e59206b6087c9d95f428f7b/test/plugins/test-trace-http2.ts#L221

**Comment by kjin** [comment]
Yes... I should have realized that `rstWithInternalError` could only be in a test. Thanks for looking into this

**Comment by kjin** [comment]
"Fixed" in #648
