### ISSUE TITLE
Error is occasionally thrown when using aws-sdk and this package

### ISSUE THREAD

**Issue by evanlucas** [GoogleCloudPlatform/cloud-trace-nodejs#684]
We currently are getting an error that looks like this:

```
/opt/app/node_modules/aws-sdk/lib/http/node.js:43
      if (stream.didCallback) return;
                 ^

TypeError: Cannot read property 'didCallback' of undefined
    at /opt/app/node_modules/aws-sdk/lib/http/node.js:43:18
    at ClientRequest.request (/opt/app/node_modules/@helpdotcom/nano/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-http.js:120:24)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.emitted (/opt/app/node_modules/@helpdotcom/nano/node_modules/emitter-listener/listener.js:134:21)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```

What appears to have actually thrown is https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L42-L52. Line 120 of the plugin-http.js is https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/plugins/plugin-http.ts#L142-L144. It looks like this happens when http.request() returns undefined. Being that http.request() is being monkey patched by this package, it made sense to me to start here. Any input on this would be greatly appreciated. Thanks!

**Comment by kjin** [comment]
Thanks for bringing this our attention! Looking at the code in question it seems odd that the `TypeError` is being thrown on line 43 but not line 54, where `stream.didCallback` is being assigned -- suggesting that either (1) `stream` is being set to undefined elsewhere, or (2) `request` was modified to run the callback synchronously. We don't introduce any synchronous invocations of the callback, and it seems like the value of `stream` is never re-assigned so could it be a different module that is also monkeypatching `http.request`?

**Comment by evanlucas** [comment]
Yea, I'm not sure how it could be possible for this to happen, but it is only happening when we have this tracing package enabled. I'm still trying to find more information.

**Comment by kjin** [comment]
Hi @evanlucas, I'm going to close this issue for housekeeping purposes. Please let us know if you have more info and I'll be happy to re-open it.
