### ISSUE TITLE
Error after updating to 2.6.0

### ISSUE THREAD

**Issue by d-winter** [GoogleCloudPlatform/cloud-trace-nodejs#712]
Hi,
after updating I get the following error:
```
ERROR:@google-cloud/trace-agent: TraceWriter#publish: Received error status code 400. Original error: ApiError: Invalid value at 'traces.traces[0].spans[0].labels[7].value' (TYPE_STRING), 9154848679131446000
Invalid value at 'traces.traces[1].spans[0].labels[7].value' (TYPE_STRING), 9154848679131446000
Invalid value at 'traces.traces[2].spans[0].labels[7].value' (TYPE_STRING), 9154848679131446000
```

I have got a very basic config, which is loaded at the very start of the app:
```
require('@google-cloud/trace-agent').start({
  enhancedDatabaseReporting: true,
  logLevel: 4,
  ignoreUrls: [/^\/healthz/, /^\/ready/], // ignore the "/healthz" and "/ready" endpoints.
});

require('./dist/system-server/main');
```

Running with the previous version does work fine.
Any idea? I saw in the changelog that empty spans are not allowed, but could not find a way how to fix the error above.

Thanks in advance
Daniel

**Comment by kjin** [comment]
Taking a look, will get back to you shortly.

**Comment by kjin** [comment]
I can reproduce this error using the [API explorer linked in the Stackdriver Trace API docs](https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects/patchTraces), but not through the Trace Agent itself. It appears to be when we send a payload where a K-V pair under the `"labels"` field has a number value. However, the [function to add labels](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v2.6.0/src/span-data.ts#L97-L103) always coerces an input value to a string, so I am curious as to how this can be happening.

As an example, I tried the following trace:

```json
{
  "traces": [
    {
      "projectId": "carrot-cake-139920",
      "traceId": "751ce64b54924298b35182b69ba6d330",
      "spans": [
        {
          "name": "/",
          "startTime": "2018-04-02T19:42:02.112Z",
          "endTime": "2018-04-02T19:42:03.302Z",
          "spanId": "1",
          "kind": "RPC_SERVER",
          "parentSpanId": "0",
          "labels": {
            "a": 12345
          }
        }
      ]
    }
  ]
}
```

which gave the following error:

```
Invalid value at 'traces.traces[0].spans[0].labels[0].value' (TYPE_STRING), 12345
```

Any additional info you can provide would be helpful as well.

**Comment by kjin** [comment]
Never mind, I've figured it out. This is indeed a bug... fix incoming.

**Comment by kjin** [comment]
@d-winter [2.6.1](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/v2.6.1/CHANGELOG.md#2018-04-02-version-261-beta-kjin) has been released. That should fix the issue!

**Comment by d-winter** [comment]
Awesome, thanks a lot for your help🙌! Will try it out later this morning.
