### ISSUE TITLE
Option to disable automatic tracing

### ISSUE THREAD

**Issue by tjmehta** [GoogleCloudPlatform/cloud-trace-nodejs#719]
Hello,

Is there any way to disable automatic tracing altogether? It would be nice if this module exposed a simple span tracing API. 

Thanks

**Comment by tjmehta** [comment]
What about an option to disable the CLS context?

**Comment by tjmehta** [comment]
I’d love to have a simple RootSpanData class that I can use to manually create child span datas (that doesn’t use CLS)

**Comment by kjin** [comment]
@tjmehta In what way is CLS not compatible with your use case? Providing an option to disable CLS is a significantly larger change and I want to make sure I understand that first before making such a change.

Would it work to writing a wrapper class around the `TraceApi` returned by `start()` that creates a new CLS context for each root span? The CLS namespace is com.google.cloud.trace.

**Comment by kjin** [comment]
Hi @tjmehta, if what I described to you doesn't work out please feel free to say so, and I'll re-open this issue.

**Comment by tjmehta** [comment]
In my experience, CLS support for various asynchronous operations is not guaranteed. It would be nice to have a simple span API that can be managed by the user without “magic”. Also, CLS’s monkey patching can lead to messier error stacks. If you are able to remove CLS from a base RootSpan class. You easily extend the class and layer CLS on top of it.

Exposing a base API would be more flexible for users to build custom app tracing helpers from.

I have modified this library in the past to expose a RootSpan class where I can “createChildSpan”s and pass the spans around my application. My http/websockets api uses the req (or socket) as a common context that is accessible by all my functions. It’s nice to avoid monkey patching when it isn’t required.

**Comment by tjmehta** [comment]
I’ll have to read this more thoroughly, but a single root context is not
what I was expecting. I was expecting something that could be used by this:
https://www.npmjs.com/package/gcloud-tracer

Will try to follow up with more details tonight

**Comment by kjin** [comment]
Ok, would my understanding be correct that you would want a `createRootSpan` or similar?

Apologies -- I should have asked for more details earlier.

**Comment by tjmehta** [comment]
I probably didn't explain with enough details. I was expecting an API to create many rootSpans as well as childSpans. For example, I would like to create a RootSpan for for each of my API's "requests" without using monkey patching. At a glance it looks like the PR only allows for one global root span, which would not work for my applications.

Each RootSpan should offer an API to create ChildSpans (without CLS, like `rootSpan.createChildSpan(..)`), so that users can manually trace any task within a "request".

**Comment by tjmehta** [comment]
I think this readme explains an API I am expecting: https://github.com/tjmehta/gcloud-tracer/tree/update-google-cloud-trace

Basically, a simple span tracing API, without monkeypatching or CLS.  I do still think monkeypatching and CLS may be useful to many users. But monkeypatching and CLS modify globals and may not work for all scenarios. Offering a base api to create root spans and child spans will be more generally useful and could be used to create more advanced OSS google cloud tracing tooling.

**Comment by kjin** [comment]
@tjmehta I think I see what you mean. Granted we had considered having a `RootSpan#createChildSpan` API before but at the time didn't consider it necessary.

It shouldn't be too complicated to introduce such an API, so I'll take a stab at it.

**Comment by kjin** [comment]
@tjmehta What do you think of the API in [this diff](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/731/files#diff-0083d751b2c247998a6ebdda46fffa61)?

**Comment by tjmehta** [comment]
@kjin looking over the PR and the offered API it does! I will know for sure once I start using it (hopefully will get to try it out this weekend).

Thanks for making these changes so quickly!

**Comment by kjin** [comment]
Sure thing, merging now!

**Comment by kjin** [comment]
Released in 2.8.0
