### ISSUE TITLE
GRPC server not being traced.

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/cloud-trace-nodejs#752]
I have the trace integration defined for two NodeJS servers, written in Typescript. One is an Express server, one is a GRPC server. 

Both have the following setup:

* Running inside GKE in a cluster that has the trace API enabled.
* Node 8.9.4
* env variable `GCLOUD_TRACE_NEW_CONTEXT=1`
* "@google-cloud/trace-agent": "2.8.1",
* "google-protobuf": "3.5.0",

The GRPC server uses:
* "grpc": "1.10.1",

I'm using the statically compiled implementation for my protos.

The Express server creates traces successfully for received requests, the GRPC one doesn't. 

GRPC server code:

```typescript
import * as _tracing from '@google-cloud/trace-agent'

_tracing.start({
  serviceContext: {
    service: 'content-service',
  },
})

import { ContentService, IContentServer } from 'lib/generated/content_service_grpc_pb'
import grpc, { Metadata, ServerUnaryCall, sendUnaryData } from 'grpc'

class Service implements IContentServer { 
  // (Definition of service handlers) 
}

const server = new grpc.Server()
server.addService(ContentService, new Service())
server.bind(`0.0.0.0:${port}`, grpc.ServerCredentials.createInsecure())
server.start()
```

**Comment by kjin** [comment]
Testing a simple gRPC server I'm able to see traces in the Cloud Platform UI. Could you try starting with warning-level logs and immediate flush (via bufferSize = 1)? E.g.

```ts
_tracing.start({
  serviceContext: {
    service: 'content-service',
  },
  logLevel: 1, // warnings
  bufferSize: 1
})
```

If that doesn't work, are there any warnings (or errors) that get printed?

**Comment by majelbstoat** [comment]
Since I added those lines, traces started appearing 🤔I know that change didn't cause that to happen, so I'm going to put this down to PEBKAC for now. Thanks for checking it out.
