### ISSUE TITLE
Update TypeScript, gts, common, etc

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-trace-nodejs#777]
There are a bunch of dependencies starting to get moldy over in package.json.  Can someone upgrade them all?

**Comment by kjin** [comment]
`gts` upgrade is going to require a semver-major change. I want to deprecate some APIs first before moving to v3, so this is blocked.

**Comment by kjin** [comment]
I'm not going to update ts or gts right now -- I don't see a need at the moment. Updated `@google-cloud/common`, though.
