### ISSUE TITLE
Tracing Spanner

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/cloud-trace-nodejs#791]
Given that the trace agent automatically traces GRPC, and, as I understand it, the Spanner client communicates with the database over GRPC, is it to be expected that Spanner tracing works out of the box? I ask, because i'm seeing some puzzling partial behaviour where traces appear to happen only sporadically.

The trace agent reliably traces when a new client session is required, using `clientMethodTrace` (the red arrow in the following):
<img width="732" alt="screenshot 2018-06-29 23 12 26" src="https://user-images.githubusercontent.com/425787/42122144-189dd706-7bf2-11e8-91a7-a0abe0db03d7.png">

```
clientMethodTrace [as createSession] (/usr/src/service/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-grpc.js:65:28)
<anonymous function> (/usr/src/service/node_modules/@google-cloud/spanner/src/v1/spanner_client.js:177:39)
```

However, it only very rarely traces the actual spanner requests for queries or mutations. In a sample of twenty reloads of the same page, for example, it only traced the spanner query once (shown here with red arrow):
<img width="755" alt="screenshot 2018-06-29 23 19 45" src="https://user-images.githubusercontent.com/425787/42122220-494c2280-7bf3-11e8-8a81-fd828d9bb486.png">

```
clientMethodTrace [as beginTransaction] (/usr/src/service/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-grpc.js:65:28)
<anonymous function> (/usr/src/service/node_modules/@google-cloud/spanner/src/v1/spanner_client.js:177:39)
```

It's hard to tell if this is to do with something in `nodejs-spanner`, something in `cloud-trace-nodejs`, my particular setup, or a transient error. There are no errors or warnings when starting up.

(And correct me if I'm wrong, but the spanner traces don't appear to be linked to their parent spans?)

```
typescript: 2.9.2
@google-cloud/spanner: 1.5.0
@google-cloud/trace-agent: 2.10.1
grpc: 1.12.4
```

**Comment by ofrobots** [comment]
Would it possible for you to share the versions of spanner and trace
libraries? Our better, the dependencies section of your package.json

**Comment by majelbstoat** [comment]
Sure:

```
  "dependencies": {
    "@google-cloud/spanner": "1.5.0",
    "@google-cloud/trace-agent": "2.10.1",
    "google-protobuf": "3.6.0",
    "grpc": "1.12.4",
    "immutable": "3.8.2",
    "p-retry": "2.0.0",
    "slate": "0.33.6",
    "unicode-length": "2.0.1"
  },
  "devDependencies": {
    "@types/bluebird": "3.5.20",
    "@types/google-protobuf": "3.2.7",
    "@types/jest": "23.1.1",
    "@types/node": "10.3.5",
    "@types/p-retry": "1.0.1",
    "@types/webpack": "4.4.2",
    "@types/webpack-node-externals": "1.6.3",
    "concurrently": "3.6.0",
    "jest": "23.1.0",
    "nodemon": "1.17.5",
    "rimraf": "2.6.2",
    "ts-loader": "4.4.1",
    "ts-node": "7.0.0",
    "typescript": "2.9.2",
    "webpack": "4.12.1",
    "webpack-cli": "3.0.8",
    "webpack-node-externals": "1.7.2"
  }
```

**Comment by majelbstoat** [comment]
To ensure the trace agent is loaded first, my webpack entry point of index.ts looks like this:

```ts
import './tracing'
import './server'
```

Which webpack turns into:

```js
/***/ "./app/server/index.ts":
/*!*****************************!*\
  !*** ./app/server/index.ts ***!
  \*****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
__webpack_require__(/*! ./tracing */ "./app/server/tracing.ts");
__webpack_require__(/*! ./server */ "./app/server/server.ts");


/***/ }),
```

**Comment by majelbstoat** [comment]
Dig more digging. I believe this might be because I was using the promise-mode of spanner, async/await, and  `GCLOUD_TRACE_NEW_CONTEXT=1` wasn't set. (It was set on the service in one world, but not another.) Adding that seems to have made things right.

**Comment by kjin** [comment]
Ok, thanks for the update. The next version of the agent (2.11) will support async/await out-of-the-box (no env var).

Please comment if you discover that `GCLOUD_TRACE_NEW_CONTEXT=1` didn't solve the problem, and I will re-open the issue. Thanks!
