### ISSUE TITLE
Discussion - should we drop nodejs-common?

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-trace-nodejs#793]
After looking around the codebase, it looks like the only part of nodejs-common that's being used is the logger.  This means that we're really unnecessarily pulling in `request` for no good reason.  Does it make sense to abstract the logging stuff in common out to it's own smaller-purpose module?

**Comment by kjin** [comment]
The `TraceWriter` class currently inherits `Service`, so for right now it seems like we are locked onto using `nodejs-common`.

**Comment by ofrobots** [comment]
I think this has been resolved as 'not yet', so I am going to close. If there is more to discuss, please reopen.
