### ISSUE TITLE
Please log the hostname on failed requests 

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-trace-nodejs#797]
I've spent the past our trying to figure out (still haven't) why am I getting these errors on Istio –which is a service mesh that requires users to explicitly whitelist all the external hosts that are called.

> ERROR:@google-cloud/trace-agent: TraceWriter#publish: Received error status code unknown. Original error: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

This error doesn't explain why it failed. `Received error status code unknown. Original error: Error: Unexpected error` might be one of the most _unhelpful_ errors to return here.

Here are some better examples:

- _Failed to upload traces: Could not retrieve credentials: could not connect to metadata service: TLS handshake failed_
- _Failed to upload traces: Could not retrieve credentials: could not connect to metadata service: unknown host metadata.google.internal_

Here's another unhelpful error:

> TraceWriter#publish: Received error status code unknown. Original error: Error: Sorry, we cannot connect to Cloud Services without a project ID. You may specify one with an environment variable named  "GOOGLE_CLOUD_PROJECT".

Why is it unhelpful? I can't tell:

- was it trying to find the project ID (from gce metadata) and that's why it failed?
- did it actually failed to connect cloudtrace.googleapis.com
  - if so, which port/protocol (grpc/https) did it use?

Here's a suggestion:

- _TraceWriter#publish: Failed to determine project ID from metadata service: unknown host metadata.google.internal_
- _TraceWriter#publish: Failed to upload traces (cloudtrace.googleapis.com:443): tls handshake failed_

**Comment by ahmetb** [comment]
Especially here's the critical part/gist of this issue:

> TraceWriter#publish: Received error status code unknown Original error: Error: Sorry, we cannot ...

**What were you trying to do** and received the error dear library.

**Comment by ofrobots** [comment]
Hi @ahmetb. Sorry for the bad error messages. We should do better. If there are there any repro steps, or details about the environment (GKE?) where this is occurrent that would be quite helpful. Also, is it possible for you to share your `package-lock.json` (privately, if you prefer). We have been fixing the error-handling behavior in some of our dependency libraries (https://github.com/stephenplusplus/gcp-metadata/pull/57) and it would be good to know precise versions you were using.

**Comment by ahmetb** [comment]
@ofrobots I hit this because my network policy/firewall was blocking accounts.google.com, GCE Metadata and *.googleapis.com. Once I whitelisted all I no longer run the issue.

But that's not the relevant part. Regardless, please try to wrap errors correctly by adding some context like "failed to do [X]: error while [Y]: exception: [reason]" to these two errors.

**Comment by ahmetb** [comment]
I'm using google-cloud/trace-agent 2.11.0.
