### ISSUE TITLE
Missing generated declarations for 'util' and 'trace-api' in current published build v.3.1.0

### ISSUE THREAD

**Issue by periklis** [GoogleCloudPlatform/cloud-trace-nodejs#840]
The current published build produces the following error messages on `tsc`:
```
node_modules/@google-cloud/trace-agent/build/src/plugin-types.d.ts:18:41 - error TS7016: Could not find a declaration file for module './trace-api'.

node_modules/@google-cloud/trace-agent/build/src/plugin-types.d.ts:20:30 - error TS7016: Could not find a declaration file for module './util'.
```
According to the [cdn cache](https://cdn.jsdelivr.net/npm/@google-cloud/trace-agent@3.1.0/build/src/) these files are really missing. However, a local try `npm run compile-all` on `v3.1.0` produces the files.

**Comment by kjin** [comment]
@periklis Fix should be out in `3.1.1`!
